// Tests for src/analyzer.mjs — session redirection analysis
import { before, after, describe, it } from "node:test";
import assert from "node:assert/strict";
import { setupTestDb, teardownTestDb, FIXTURES } from "./test-helpers.mjs";

const testData = {
  sessions: [
    ...FIXTURES.redirectionSession.sessions,
    ...FIXTURES.cleanSession.sessions,
    ...FIXTURES.mixedAutoSession.sessions,
    // Tiny session with only 1 turn — should be skipped by analyzeRecent
    { id: "sess-tiny", repository: "org/my-app", branch: "tiny", summary: "Tiny", created_at: "2025-01-19T10:00:00Z" },
  ],
  turns: [
    ...FIXTURES.redirectionSession.turns,
    ...FIXTURES.cleanSession.turns,
    ...FIXTURES.mixedAutoSession.turns,
    { session_id: "sess-tiny", turn_index: 0, user_message: "Hello", assistant_response: "Hi!" },
  ],
  files: [
    ...FIXTURES.redirectionSession.files,
    ...(FIXTURES.cleanSession.files || []),
  ],
  refs: [
    ...(FIXTURES.cleanSession.refs || []),
  ],
};

let analyzeSession, analyzeRecent, findTopPatterns;

before(async () => {
  setupTestDb(testData);
  const mod = await import("../src/analyzer.mjs");
  analyzeSession = mod.analyzeSession;
  analyzeRecent = mod.analyzeRecent;
  findTopPatterns = mod.findTopPatterns;
});

after(() => { teardownTestDb(); });

// ── analyzeSession ──────────────────────────────────────────────

describe("analyzeSession", () => {
  it("returns null for non-existent session ID", () => {
    assert.equal(analyzeSession("does-not-exist"), null);
  });

  it("returns correct session metadata", () => {
    const report = analyzeSession("sess-redirect-1");
    assert.equal(report.session.id, "sess-redirect-1");
    assert.equal(report.session.repository, "org/my-app");
    assert.equal(report.session.branch, "feature-auth");
    assert.equal(report.session.summary, "Add auth module");
    assert.ok(report.session.createdAt);
    assert.equal(report.session.turnCount, 5);
  });

  it("detects redirections in the redirection session", () => {
    const report = analyzeSession("sess-redirect-1");
    assert.equal(report.stats.totalRedirections, 3);
    const turnIndices = report.redirections.map((r) => r.turnIndex);
    assert.deepEqual(turnIndices, [1, 2, 3]);
  });

  it("turn 1 matches explicit_correction (no, don't)", () => {
    const report = analyzeSession("sess-redirect-1");
    const r1 = report.redirections.find((r) => r.turnIndex === 1);
    assert.ok(r1);
    assert.ok(r1.matches.some((m) => m.category === "explicit_correction"));
  });

  it("turn 2 matches explicit_correction (that's wrong)", () => {
    const report = analyzeSession("sess-redirect-1");
    const r2 = report.redirections.find((r) => r.turnIndex === 2);
    assert.ok(r2);
    assert.ok(r2.matches.some((m) => m.category === "explicit_correction"));
  });

  it("turn 3 matches course_change (actually, instead)", () => {
    const report = analyzeSession("sess-redirect-1");
    const r3 = report.redirections.find((r) => r.turnIndex === 3);
    assert.ok(r3);
    assert.ok(r3.matches.some((m) => m.category === "course_change"));
    assert.equal(r3.matches.length, 2); // "actually" and "instead"
  });

  it("counts autoGeneratedCount correctly (mixedAutoSession)", () => {
    const report = analyzeSession("sess-mixed-1");
    // Turns 0 and 2 are auto-generated (cross_session_message, system_notification)
    assert.equal(report.stats.autoGeneratedCount, 2);
  });

  it("redirectionRate = redirections / humanTurnCount", () => {
    const report = analyzeSession("sess-redirect-1");
    // 3 redirections out of 5 human turns (none are auto-generated)
    assert.equal(report.stats.redirectionRate, 3 / 5);
  });

  it("computes redirectionRate for mixed-auto session", () => {
    const report = analyzeSession("sess-mixed-1");
    // 4 total turns, 2 auto-generated → 2 human turns, 1 redirection
    assert.equal(report.stats.userTurnCount, 2);
    assert.equal(report.stats.redirectionRate, 1 / 2);
  });

  it("detects file thrashing (auth/index.js edited 3+ times)", () => {
    const report = analyzeSession("sess-redirect-1");
    assert.equal(report.stats.thrashedFileCount, 1);
    assert.ok(report.thrashedFiles.some((f) => f.file_path === "src/auth/index.js"));
  });

  it("returns categoryBreakdown with counts per category", () => {
    const report = analyzeSession("sess-redirect-1");
    assert.ok(report.categoryBreakdown.explicit_correction);
    assert.ok(report.categoryBreakdown.course_change);
    assert.equal(report.categoryBreakdown.explicit_correction.count, 2);
    assert.equal(report.categoryBreakdown.course_change.count, 2);
  });

  it("clean session has 0 redirections", () => {
    const report = analyzeSession("sess-clean-1");
    assert.equal(report.stats.totalRedirections, 0);
    assert.equal(report.redirections.length, 0);
    assert.equal(report.stats.redirectionRate, 0);
    assert.deepEqual(report.categoryBreakdown, {});
  });

  it("cleans auto-generated session summary", () => {
    const report = analyzeSession("sess-mixed-1");
    // The session summary is a cross_session_message, so cleanSummary
    // replaces it with the first human turn
    assert.equal(report.session.summary, "The login form crashes on empty email");
  });

  it("each redirection includes weight and message", () => {
    const report = analyzeSession("sess-redirect-1");
    for (const r of report.redirections) {
      assert.ok(typeof r.weight === "number");
      assert.ok(r.weight > 0);
      assert.ok(typeof r.message === "string");
      assert.ok(r.message.length > 0);
    }
  });

  it("totalWeight sums all match weights", () => {
    const report = analyzeSession("sess-redirect-1");
    const expectedWeight = report.redirections.reduce((s, r) => s + r.weight, 0);
    assert.equal(report.stats.totalWeight, expectedWeight);
    assert.ok(report.stats.totalWeight > 0);
  });
});

// ── analyzeRecent ───────────────────────────────────────────────

describe("analyzeRecent", () => {
  it("returns aggregate stats", () => {
    const result = analyzeRecent({ repo: "org/my-app" });
    assert.ok(result.aggregate);
    assert.ok(typeof result.aggregate.sessionsAnalyzed === "number");
    assert.ok(typeof result.aggregate.sessionsWithRedirections === "number");
    assert.ok(typeof result.aggregate.totalRedirections === "number");
    assert.ok(typeof result.aggregate.avgRedirectionRate === "number");
    assert.ok(result.aggregate.categoryTotals);
  });

  it("skips sessions with < 2 turns", () => {
    const result = analyzeRecent({ repo: "org/my-app" });
    // sess-tiny has 1 turn and should be skipped from analysis
    const sessionIds = result.sessions.map((s) => s.session.id);
    assert.ok(!sessionIds.includes("sess-tiny"));
  });

  it("only returns sessions with redirections", () => {
    const result = analyzeRecent({ repo: "org/my-app" });
    // sess-clean-1 has 0 redirections → excluded
    const sessionIds = result.sessions.map((s) => s.session.id);
    assert.ok(!sessionIds.includes("sess-clean-1"));
    // sess-redirect-1 has redirections → included
    assert.ok(sessionIds.includes("sess-redirect-1"));
  });

  it("sorts sessions by weight descending", () => {
    const result = analyzeRecent({ repo: "org/my-app" });
    for (let i = 1; i < result.sessions.length; i++) {
      assert.ok(
        result.sessions[i - 1].stats.totalWeight >= result.sessions[i].stats.totalWeight
      );
    }
  });

  it("sessionsAnalyzed counts all non-skipped sessions", () => {
    const result = analyzeRecent({ repo: "org/my-app" });
    // 4 sessions match repo, but sessionsAnalyzed = total returned by listSessions
    assert.ok(result.aggregate.sessionsAnalyzed >= 2);
  });
});

// ── findTopPatterns ─────────────────────────────────────────────

describe("findTopPatterns", () => {
  it("returns patterns sorted by count descending", () => {
    const patterns = findTopPatterns({ repo: "org/my-app" });
    assert.ok(Array.isArray(patterns));
    for (let i = 1; i < patterns.length; i++) {
      assert.ok(patterns[i - 1].count >= patterns[i].count);
    }
  });

  it("each pattern has label, category, count, and examples", () => {
    const patterns = findTopPatterns({ repo: "org/my-app" });
    assert.ok(patterns.length > 0);
    for (const p of patterns) {
      assert.ok(typeof p.label === "string");
      assert.ok(typeof p.category === "string");
      assert.ok(typeof p.count === "number");
      assert.ok(Array.isArray(p.examples));
      assert.ok(p.examples.length > 0);
    }
  });

  it("examples include sessionId and message", () => {
    const patterns = findTopPatterns({ repo: "org/my-app" });
    for (const p of patterns) {
      for (const ex of p.examples) {
        assert.ok(typeof ex.sessionId === "string");
        assert.ok(typeof ex.message === "string");
      }
    }
  });
});
