// Tests for src/autogenerated.mjs — auto-generated prompt detection
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { isAutoGenerated, AUTOGENERATED_TAG, cleanSummary } from "../src/autogenerated.mjs";

describe("isAutoGenerated", () => {
  describe("returns true for system-injected messages", () => {
    it("detects [[PLAN]] prefix", () => {
      assert.ok(isAutoGenerated("[[PLAN]] implement the auth module"));
    });

    it("detects <system_notification> tags", () => {
      assert.ok(isAutoGenerated("<system_notification>Shell command completed</system_notification>"));
    });

    it("detects <cross_session_message> tags", () => {
      assert.ok(
        isAutoGenerated(
          '<cross_session_message from_project_session_id="abc-123">Status update: tests pass</cross_session_message>'
        )
      );
    });

    it("detects <agent_merge_tick> tags", () => {
      assert.ok(isAutoGenerated("<agent_merge_tick>check-in</agent_merge_tick>"));
    });

    it("detects <automated_*> tags", () => {
      assert.ok(isAutoGenerated("<automated_check>CI status green</automated_check>"));
    });

    it("detects datetime-only messages", () => {
      assert.ok(isAutoGenerated("<current_datetime>2026-04-18T15:37:25.924Z</current_datetime>"));
    });

    it("detects messages that are entirely XML with no user content", () => {
      assert.ok(isAutoGenerated("<some_tag>content here</some_tag>"));
    });

    it("handles messages with leading/trailing whitespace", () => {
      assert.ok(isAutoGenerated("  [[PLAN]] do the thing  "));
      assert.ok(isAutoGenerated("  <system_notification>done</system_notification>  "));
    });
  });

  describe("returns false for human-written messages", () => {
    it("rejects normal prompts", () => {
      assert.ok(!isAutoGenerated("fix the bug in src/auth.ts"));
    });

    it("rejects prompts with inline code", () => {
      assert.ok(!isAutoGenerated("the <div> element should have a className"));
    });

    it("rejects prompts mentioning system concepts", () => {
      assert.ok(!isAutoGenerated("I got a notification that the build failed"));
    });

    it("rejects prompts with backticks and tags in context", () => {
      assert.ok(
        !isAutoGenerated(
          "Please update the handler so it returns 200. The current code in src/api.ts is wrong."
        )
      );
    });

    it("rejects short prompts", () => {
      assert.ok(!isAutoGenerated("fix the bug"));
    });

    it("rejects empty/null/undefined", () => {
      assert.ok(!isAutoGenerated(""));
      assert.ok(!isAutoGenerated(null));
      assert.ok(!isAutoGenerated(undefined));
    });

    it("rejects non-string values", () => {
      assert.ok(!isAutoGenerated(42));
      assert.ok(!isAutoGenerated({}));
    });

    it("rejects messages with datetime prefix but also human content", () => {
      assert.ok(
        !isAutoGenerated(
          "<current_datetime>2026-04-18T15:37:25.924Z</current_datetime>\nfix the login bug"
        )
      );
    });
  });
});

describe("AUTOGENERATED_TAG", () => {
  it("has required properties", () => {
    assert.equal(AUTOGENERATED_TAG.type, "auto_generated");
    assert.ok(AUTOGENERATED_TAG.emoji);
    assert.ok(AUTOGENERATED_TAG.label);
    assert.ok(AUTOGENERATED_TAG.color);
  });
});

describe("cleanSummary", () => {
  it("returns normal summary unchanged", () => {
    assert.equal(cleanSummary("Fix the login bug"), "Fix the login bug");
  });

  it("returns null for null summary", () => {
    assert.equal(cleanSummary(null), null);
  });

  it("returns null for undefined summary", () => {
    assert.equal(cleanSummary(undefined), undefined);
  });

  it("replaces cross_session_message summary with first human turn", () => {
    const summary = "<cross_session_message>\nfrom_session_id: abc\n</cross_session_message>";
    const turns = [
      { user_message: "<cross_session_message>\nfrom_session_id: abc\n</cross_session_message>" },
      { user_message: "Fix the login bug in auth.ts" },
    ];
    assert.equal(cleanSummary(summary, turns), "Fix the login bug in auth.ts");
  });

  it("replaces system_notification summary with first human turn", () => {
    const summary = "<system_notification>Session completed</system_notification>";
    const turns = [
      { user_message: "<system_notification>Session completed</system_notification>" },
      { user_message: "what happened?" },
    ];
    assert.equal(cleanSummary(summary, turns), "what happened?");
  });

  it("returns null when no human turns exist", () => {
    const summary = "<cross_session_message>\nfrom_session_id: abc\n</cross_session_message>";
    const turns = [
      { user_message: "<cross_session_message>\nfrom_session_id: abc\n</cross_session_message>" },
      { user_message: "<system_notification>done</system_notification>" },
    ];
    assert.equal(cleanSummary(summary, turns), null);
  });

  it("truncates long human fallback to 200 chars", () => {
    const summary = "[[PLAN]] do the thing";
    const longMsg = "A".repeat(300);
    const turns = [{ user_message: longMsg }];
    assert.equal(cleanSummary(summary, turns).length, 200);
  });

  it("skips auto-generated turns to find first human turn", () => {
    const summary = "<cross_session_message>\nstuff\n</cross_session_message>";
    const turns = [
      { user_message: "<cross_session_message>\nstuff\n</cross_session_message>" },
      { user_message: "[[PLAN]] plan mode message" },
      { user_message: "Can you fix the CSS on the homepage?" },
    ];
    assert.equal(cleanSummary(summary, turns), "Can you fix the CSS on the homepage?");
  });
});
