// Tests for src/autogenerated.mjs — auto-generated prompt detection
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { isAutoGenerated, AUTOGENERATED_TAG } from "../src/autogenerated.mjs";

describe("isAutoGenerated", () => {
  describe("returns true for system-injected messages", () => {
    it("detects [[PLAN]] prefix", () => {
      assert.ok(isAutoGenerated("[[PLAN]] implement the auth module"));
    });

    it("detects <system_notification> tags", () => {
      assert.ok(isAutoGenerated("<system_notification>Shell command completed</system_notification>"));
    });

    it("detects <cross_session_message> tags", () => {
      assert.ok(
        isAutoGenerated(
          '<cross_session_message from_project_session_id="abc-123">Status update: tests pass</cross_session_message>'
        )
      );
    });

    it("detects <agent_merge_tick> tags", () => {
      assert.ok(isAutoGenerated("<agent_merge_tick>check-in</agent_merge_tick>"));
    });

    it("detects <automated_*> tags", () => {
      assert.ok(isAutoGenerated("<automated_check>CI status green</automated_check>"));
    });

    it("detects datetime-only messages", () => {
      assert.ok(isAutoGenerated("<current_datetime>2026-04-18T15:37:25.924Z</current_datetime>"));
    });

    it("detects messages that are entirely XML with no user content", () => {
      assert.ok(isAutoGenerated("<some_tag>content here</some_tag>"));
    });

    it("handles messages with leading/trailing whitespace", () => {
      assert.ok(isAutoGenerated("  [[PLAN]] do the thing  "));
      assert.ok(isAutoGenerated("  <system_notification>done</system_notification>  "));
    });
  });

  describe("returns false for human-written messages", () => {
    it("rejects normal prompts", () => {
      assert.ok(!isAutoGenerated("fix the bug in src/auth.ts"));
    });

    it("rejects prompts with inline code", () => {
      assert.ok(!isAutoGenerated("the <div> element should have a className"));
    });

    it("rejects prompts mentioning system concepts", () => {
      assert.ok(!isAutoGenerated("I got a notification that the build failed"));
    });

    it("rejects prompts with backticks and tags in context", () => {
      assert.ok(
        !isAutoGenerated(
          "Please update the handler so it returns 200. The current code in src/api.ts is wrong."
        )
      );
    });

    it("rejects short prompts", () => {
      assert.ok(!isAutoGenerated("fix the bug"));
    });

    it("rejects empty/null/undefined", () => {
      assert.ok(!isAutoGenerated(""));
      assert.ok(!isAutoGenerated(null));
      assert.ok(!isAutoGenerated(undefined));
    });

    it("rejects non-string values", () => {
      assert.ok(!isAutoGenerated(42));
      assert.ok(!isAutoGenerated({}));
    });

    it("rejects messages with datetime prefix but also human content", () => {
      assert.ok(
        !isAutoGenerated(
          "<current_datetime>2026-04-18T15:37:25.924Z</current_datetime>\nfix the login bug"
        )
      );
    });
  });
});

describe("AUTOGENERATED_TAG", () => {
  it("has required properties", () => {
    assert.equal(AUTOGENERATED_TAG.type, "auto_generated");
    assert.ok(AUTOGENERATED_TAG.emoji);
    assert.ok(AUTOGENERATED_TAG.label);
    assert.ok(AUTOGENERATED_TAG.color);
  });
});
