// Tests for src/replay.mjs — session replay with coaching annotations
import { before, after, describe, it } from "node:test";
import assert from "node:assert/strict";
import { setupTestDb, teardownTestDb, FIXTURES } from "./test-helpers.mjs";

const testData = {
  sessions: [
    ...FIXTURES.redirectionSession.sessions,
    ...FIXTURES.cleanSession.sessions,
    ...FIXTURES.mixedAutoSession.sessions,
  ],
  turns: [
    ...FIXTURES.redirectionSession.turns,
    ...FIXTURES.cleanSession.turns,
    ...FIXTURES.mixedAutoSession.turns,
  ],
  files: [
    ...FIXTURES.redirectionSession.files,
    ...(FIXTURES.cleanSession.files || []),
  ],
};

let annotateSession;

before(async () => {
  setupTestDb(testData);
  const mod = await import("../src/replay.mjs");
  annotateSession = mod.annotateSession;
});

after(() => { teardownTestDb(); });

// ── annotateSession ─────────────────────────────────────────────

describe("annotateSession", () => {
  it("returns an object with empty turns for non-existent session", () => {
    // annotateSession does not check session existence — it processes turns
    // which will be an empty array for a non-existent session
    const result = annotateSession("does-not-exist");
    assert.ok(result);
    assert.equal(result.sessionId, "does-not-exist");
    assert.equal(result.turns.length, 0);
  });

  it("returns correct sessionId", () => {
    const result = annotateSession("sess-redirect-1");
    assert.equal(result.sessionId, "sess-redirect-1");
  });

  it("each turn has turnIndex, userMessage, and tags array", () => {
    const result = annotateSession("sess-redirect-1");
    for (const turn of result.turns) {
      assert.ok(typeof turn.turnIndex === "number");
      assert.ok(typeof turn.userMessage === "string");
      assert.ok(Array.isArray(turn.tags));
    }
  });

  it("includes assistantResponse and timestamp per turn", () => {
    const result = annotateSession("sess-redirect-1");
    for (const turn of result.turns) {
      assert.ok("assistantResponse" in turn);
      assert.ok("timestamp" in turn);
    }
  });

  it("redirection session: 'No, don't use passport' has no replay redirection tag", () => {
    // replay.mjs CORRECTION_RE uses trailing \b which doesn't match "no," (non-word boundary)
    // This is different from analyzer.mjs which uses patterns.mjs with different regexes
    const result = annotateSession("sess-redirect-1");
    const turn1 = result.turns.find((t) => t.turnIndex === 1);
    assert.ok(turn1);
    assert.ok(
      !turn1.tags.some((tag) => tag.type === "redirection"),
      "Turn 1 should NOT have a redirection tag (CORRECTION_RE trailing \\b)"
    );
  });

  it("redirection session: 'That's wrong' gets redirection tag", () => {
    const result = annotateSession("sess-redirect-1");
    const turn2 = result.turns.find((t) => t.turnIndex === 2);
    assert.ok(turn2);
    assert.ok(turn2.tags.some((tag) => tag.type === "redirection"));
  });

  it("redirection session: 'Actually, use bcrypt' gets redirection tag", () => {
    const result = annotateSession("sess-redirect-1");
    const turn3 = result.turns.find((t) => t.turnIndex === 3);
    assert.ok(turn3);
    assert.ok(turn3.tags.some((tag) => tag.type === "redirection"));
  });

  it("auto-generated turns are excluded from turns array", () => {
    const result = annotateSession("sess-mixed-1");
    // Turns 0 and 2 are auto-generated and should be excluded
    const indices = result.turns.map((t) => t.turnIndex);
    assert.ok(!indices.includes(0), "Turn 0 (cross_session_message) should be excluded");
    assert.ok(!indices.includes(2), "Turn 2 (system_notification) should be excluded");
    // Human turns 1 and 3 should be included
    assert.ok(indices.includes(1));
    assert.ok(indices.includes(3));
  });

  it("summary.autoGenerated counts excluded turns", () => {
    const result = annotateSession("sess-mixed-1");
    assert.equal(result.summary.autoGenerated, 2);
  });

  it("summary.totalTurns counts all DB turns (not just human)", () => {
    // The code uses turns.length (all turns from the DB)
    const result = annotateSession("sess-mixed-1");
    assert.equal(result.summary.totalTurns, 4);
  });

  it("summary has an overallGrade (A-F)", () => {
    const result = annotateSession("sess-redirect-1");
    assert.ok(["A", "B", "C", "D"].includes(result.summary.overallGrade));
  });

  it("clean session gets grade A", () => {
    const result = annotateSession("sess-clean-1");
    assert.equal(result.summary.overallGrade, "A");
  });

  it("redirection session gets grade B (2 redirections in replay)", () => {
    // replay.mjs only detects 2 redirections (turns 2,3) — turn 1 "No, don't" is missed
    const result = annotateSession("sess-redirect-1");
    assert.equal(result.summary.redirections, 2);
    assert.equal(result.summary.overallGrade, "B");
  });

  it("summary has topCoachingTip string", () => {
    const result = annotateSession("sess-redirect-1");
    assert.ok(typeof result.summary.topCoachingTip === "string");
    assert.ok(result.summary.topCoachingTip.length > 0);
  });

  it("clean session topCoachingTip is positive", () => {
    const result = annotateSession("sess-clean-1");
    assert.match(result.summary.topCoachingTip, /Solid session/i);
  });

  it("'Looks good, ship it' gets approval tag", () => {
    const result = annotateSession("sess-redirect-1");
    const turn4 = result.turns.find((t) => t.turnIndex === 4);
    assert.ok(turn4);
    assert.ok(turn4.tags.some((tag) => tag.type === "approval"));
  });

  it("initial 'Create' turn gets good_delegation tag", () => {
    const result = annotateSession("sess-redirect-1");
    const turn0 = result.turns.find((t) => t.turnIndex === 0);
    assert.ok(turn0);
    assert.ok(turn0.tags.some((tag) => tag.type === "good_delegation"));
  });

  it("redirection turns have coachingTip", () => {
    const result = annotateSession("sess-redirect-1");
    const redirectionTurns = result.turns.filter((t) =>
      t.tags.some((tag) => tag.type === "redirection")
    );
    assert.ok(redirectionTurns.length > 0);
    for (const turn of redirectionTurns) {
      assert.ok(typeof turn.coachingTip === "string", "Expected coachingTip on redirection turn");
    }
  });

  it("mixed session: 'Go back' gets redirection tag", () => {
    const result = annotateSession("sess-mixed-1");
    const turn3 = result.turns.find((t) => t.turnIndex === 3);
    assert.ok(turn3);
    assert.ok(turn3.tags.some((tag) => tag.type === "redirection"));
  });

  it("summary counts match the annotated turns", () => {
    const result = annotateSession("sess-redirect-1");
    let redirectionCount = 0;
    let approvalCount = 0;
    for (const turn of result.turns) {
      for (const tag of turn.tags) {
        if (tag.type === "redirection") redirectionCount++;
        if (tag.type === "approval") approvalCount++;
      }
    }
    assert.equal(result.summary.redirections, redirectionCount);
    assert.equal(result.summary.approvals, approvalCount);
  });
});
