changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "📦 Dependencies"
      labels:
        - dependencies
    - title: "📝 Documentation"
      labels:
        - documentation
    - title: "🔧 Maintenance"
      labels:
        - chore
        - maintenance
    - title: "Other Changes"
      labels:
        - "*"
