// Express API server for the Copilot Insights dashboard.
// Wraps the shared analysis modules and serves data to the React frontend.

import express from "express";
import cors from "cors";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  analyzeSession,
  analyzeRecent,
  findTopPatterns,
} from "../src/analyzer.mjs";
import { generateSuggestions } from "../src/suggestions.mjs";
import { analyzeSprawl } from "../src/sprawl.mjs";
import { analyzeFirstTurnClarity } from "../src/clarity.mjs";
import { analyzeEfficiency, analyzeEfficiencyBatch } from "../src/efficiency.mjs";
import {
  hourlyProductivity,
  promptLengthAnalysis,
  repoHealth,
  hotFiles,
  sessionDepth,
  toolUsage,
} from "../src/analytics.mjs";
import { analyzeInstructionGaps } from "../src/instructions.mjs";
import { analyzeInstructionFailures } from "../src/instruction-failures.mjs";
import { analyzeDelegation } from "../src/delegation.mjs";
import { analyzeJudgment } from "../src/judgment.mjs";
import { generateDevPlan, generateProgressCheck, generateRetro } from "../src/dev-plan.mjs";
import { computePillarTrends } from "../src/trends.mjs";
import { annotateSession } from "../src/replay.mjs";
import { analyzeWorkStyle } from "../src/work-style.mjs";
import { computeSessionComplexity, computeCreateEditRatio, computeFileTypeDiversity } from "../src/session-insights.mjs";

import { listSessions, getSessionTurns, getSessionRefs, getDb } from "../src/db.mjs";
import { matchPatterns, REDIRECTION_CATEGORIES } from "../src/patterns.mjs";
import { analyzePrompt } from "../src/practice.mjs";
import { isAutoGenerated } from "../src/autogenerated.mjs";
import CHALLENGE_LIBRARY from "../src/challenge-library.mjs";
import { DEFAULT_PORT } from "../src/defaults.mjs";
import { log } from "../src/log.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const app = express();
const PORT = process.env.PORT || DEFAULT_PORT;

app.use(cors({ origin: /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/ }));
app.use(express.json({ limit: "50kb" }));

// Serve static UI build in production
const uiDist = resolve(__dirname, "..", "ui", "dist");
app.use(express.static(uiDist));

// ΓöÇΓöÇ API Routes ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

/**
 * Convert a timeframe string (7d, 30d, 90d, all) to an ISO date.
 */
function parseSince(timeframe) {
  if (!timeframe || timeframe === "all") return undefined;
  const match = timeframe.match(/^(\d+)d$/);
  if (!match) return undefined;
  const days = parseInt(match[1]);
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}


/** Accepted timeframe patterns: digits + d/w/m/y, or "all". */
const TIMEFRAME_RE = /^(?:\d{1,4}[dwmy]|all)$/;

/**
 * Validate the `repo` query parameter — must be a non-empty string if present.
 * Returns the validated repo string or undefined.
 */
function validateRepo(req, res) {
  const repo = req.query.repo;
  if (repo === undefined || repo === "") return undefined;
  if (typeof repo !== "string") {
    res.status(400).json({ error: "Invalid 'repo' parameter — must be a string" });
    return null;
  }
  return repo;
}

/**
 * Validate and parse the `timeframe` query parameter.
 * Returns the ISO date string, undefined (for "all"), or null on validation failure.
 */
function validateTimeframe(req, res) {
  const tf = req.query.timeframe;
  if (!tf || tf === "all") return undefined;
  if (typeof tf !== "string" || !TIMEFRAME_RE.test(tf)) {
    res.status(400).json({ error: "Invalid 'timeframe' parameter — use format like '7d', '30d', or 'all'" });
    return null;
  }
  return parseSince(tf);
}

/**
 * Standardized route error handler — logs context and sends 500.
 */
function handleRouteError(res, err, route) {
  log.error(`[${route}]`, err);
  res.status(500).json({ error: "Internal server error" });
}
// ΓöÇΓöÇ Session Hiding (in-memory) ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

const hiddenSessions = new Set();
const MAX_HIDDEN = 5000;
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * GET /api/hidden-sessions
 * Return list of session IDs currently hidden from analysis.
 * Hidden sessions are stored in-memory only ΓÇö cleared on server restart.
 */
app.get("/api/hidden-sessions", (_req, res) => {
  res.json({ sessionIds: [...hiddenSessions] });
});

/**
 * POST /api/sessions/:id/hide
 * Add a session ID to the hidden set (in-memory only).
 * Returns 400 if ID is not a valid UUID v4, 429 if cap reached.
 */
app.post("/api/sessions/:id/hide", (req, res) => {
  const { id } = req.params;
  if (!UUID_RE.test(id)) {
    return res.status(400).json({ error: "Invalid session ID format" });
  }
  if (hiddenSessions.size >= MAX_HIDDEN && !hiddenSessions.has(id)) {
    return res.status(429).json({ error: "Hidden sessions limit reached" });
  }
  hiddenSessions.add(id);
  res.json({ ok: true });
});

/**
 * DELETE /api/sessions/:id/hide
 * Remove a session ID from the hidden set.
 * Returns 400 if ID is not a valid UUID v4.
 */
app.delete("/api/sessions/:id/hide", (req, res) => {
  const { id } = req.params;
  if (!UUID_RE.test(id)) {
    return res.status(400).json({ error: "Invalid session ID format" });
  }
  hiddenSessions.delete(id);
  res.json({ ok: true });
});

/**
 * GET /api/summary
 * Aggregate redirection stats across recent sessions.
 */
app.get("/api/summary", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const result = analyzeRecent({ repo, since, excludeIds: hiddenSessions });
    res.json(result.aggregate);
  } catch (err) {
    handleRouteError(res, err, "GET /api/summary");
  }
});

/**
 * GET /api/sessions
 * List sessions with redirection scores, ranked by severity.
 */
app.get("/api/sessions", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const result = analyzeRecent({ repo, since, excludeIds: hiddenSessions });

    const sessions = result.sessions.map((s) => ({
      id: s.session.id,
      repository: s.session.repository,
      branch: s.session.branch,
      summary: s.session.summary,
      createdAt: s.session.createdAt,
      turnCount: s.session.turnCount,
      redirectionCount: s.stats.totalRedirections,
      redirectionRate: s.stats.redirectionRate,
      totalWeight: s.stats.totalWeight,
      thrashedFileCount: s.stats.thrashedFileCount,
      categoryBreakdown: s.categoryBreakdown,
    }));

    res.json({ sessions, aggregate: result.aggregate });
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions");
  }
});

/**
 * GET /api/sessions/:id
 * Detailed analysis of a single session.
 */
app.get("/api/sessions/:id", (req, res) => {
  try {
    const report = analyzeSession(req.params.id);
    if (!report) {
      return res.status(404).json({ error: "Session not found" });
    }
    res.json(report);
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions/:id");
  }
});

/**
 * GET /api/patterns
 * Top redirection patterns across sessions.
 */
app.get("/api/patterns", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const patterns = findTopPatterns({ repo, since, excludeIds: hiddenSessions });
    res.json({ patterns });
  } catch (err) {
    handleRouteError(res, err, "GET /api/patterns");
  }
});

/**
 * GET /api/trends
 * Redirection rates bucketed by date for trend charting.
 */
app.get("/api/trends", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const result = analyzeRecent({ repo, since, excludeIds: hiddenSessions });

    // Bucket sessions by date
    const buckets = {};
    for (const s of result.sessions) {
      const date = s.session.createdAt?.split("T")[0] || "unknown";
      if (!buckets[date]) {
        buckets[date] = {
          date,
          sessionCount: 0,
          totalRedirections: 0,
          totalTurns: 0,
          totalWeight: 0,
        };
      }
      buckets[date].sessionCount++;
      buckets[date].totalRedirections += s.stats.totalRedirections;
      buckets[date].totalTurns += s.stats.userTurnCount;
      buckets[date].totalWeight += s.stats.totalWeight;
    }

    const trends = Object.values(buckets)
      .map((b) => ({
        ...b,
        redirectionRate:
          b.totalTurns > 0 ? b.totalRedirections / b.totalTurns : 0,
      }))
      .sort((a, b) => a.date.localeCompare(b.date));

    res.json({ trends });
  } catch (err) {
    handleRouteError(res, err, "unknown");
  }
});

/**
 * GET /api/insights
 * Actionable prompting tips derived from redirection data.
 */
app.get("/api/insights", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const result = analyzeRecent({ repo, since, excludeIds: hiddenSessions });
    const patterns = findTopPatterns({ repo, since, excludeIds: hiddenSessions });

    const insights = generateInsights(result, patterns);
    res.json({ insights });
  } catch (err) {
    handleRouteError(res, err, "GET /api/insights");
  }
});

/**
 * GET /api/suggestions
 * Prompt rewrite suggestions based on actual redirections.
 */
app.get("/api/suggestions", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const data = generateSuggestions({ repo, since, excludeIds: hiddenSessions });
    res.json({ suggestions: data });
  } catch (err) {
    handleRouteError(res, err, "GET /api/suggestions");
  }
});

// ΓöÇΓöÇ Insight Generation ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

/**
 * GET /api/sessions/:id/sprawl
 * Sprawl analysis for a single session.
 */
app.get("/api/sessions/:id/sprawl", (req, res) => {
  try {
    const result = analyzeSprawl(req.params.id);
    if (!result) return res.json({ sprawl: null, message: "Session too short to analyze" });
    res.json(result);
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions/:id/sprawl");
  }
});

/**
 * GET /api/sessions/:id/efficiency
 * Efficiency analysis for a single session.
 */
app.get("/api/sessions/:id/efficiency", (req, res) => {
  try {
    const turns = getSessionTurns(req.params.id);
    const refs = getSessionRefs(req.params.id);
    const result = analyzeEfficiency(turns, refs);
    if (!result) return res.json({ efficiency: null, message: "Session too short to analyze" });
    res.json(result);
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions/:id/efficiency");
  }
});

/**
 * GET /api/clarity
 * First-turn clarity analysis across sessions.
 */
app.get("/api/clarity", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const sessions = listSessions({ repo, since, excludeIds: hiddenSessions });
    const result = analyzeFirstTurnClarity(
      sessions.filter((s) => s.turn_count >= 2),
      getSessionTurns
    );
    res.json(result);
  } catch (err) {
    handleRouteError(res, err, "GET /api/clarity");
  }
});

/**
 * GET /api/efficiency
 * Turn efficiency analysis across sessions.
 */
app.get("/api/efficiency", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const sessions = listSessions({ repo, since, excludeIds: hiddenSessions });
    const sessionsData = sessions
      .filter((s) => s.turn_count >= 2)
      .map((s) => ({
        session: s,
        turns: getSessionTurns(s.id),
        refs: getSessionRefs(s.id),
      }));
    const result = analyzeEfficiencyBatch(sessionsData);
    res.json(result);
  } catch (err) {
    handleRouteError(res, err, "GET /api/efficiency");
  }
});

// ΓöÇΓöÇ Analytics endpoints ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

/**
 * GET /api/analytics/hourly
 * Turns and redirection rate by hour of day.
 */
app.get("/api/analytics/hourly", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(hourlyProductivity({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/hourly");
  }
});

/**
 * GET /api/analytics/prompt-length
 * Redirection rate by prompt length bucket.
 */
app.get("/api/analytics/prompt-length", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(promptLengthAnalysis({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/prompt-length");
  }
});

/**
 * GET /api/analytics/repos
 * Per-repo session counts and redirection rates.
 */
app.get("/api/analytics/repos", (req, res) => {
  try {
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(repoHealth({ since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/repos");
  }
});

/**
 * GET /api/analytics/hot-files
 * Most-touched files across sessions.
 */
app.get("/api/analytics/hot-files", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(hotFiles({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/hot-files");
  }
});

/**
 * GET /api/analytics/depth
 * Session depth distribution.
 */
app.get("/api/analytics/depth", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(sessionDepth({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/depth");
  }
});

/**
 * GET /api/analytics/tools
 * Tool usage breakdown (create vs edit).
 */
app.get("/api/analytics/tools", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(toolUsage({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/tools");
  }
});

/**
 * GET /api/instruction-gaps
 * Instruction file gap analysis ΓÇö repeated conventions that should be codified.
 */
app.get("/api/instruction-gaps", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(analyzeInstructionGaps({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/instruction-gaps");
  }
});

/**
 * GET /api/instruction-failures
 * Instruction failure analysis ΓÇö rules that exist but agent ignores/forgets.
 */
app.get("/api/instruction-failures", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(analyzeInstructionFailures({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/instruction-failures");
  }
});

/**
 * GET /api/delegation
 * Delegation analysis ΓÇö how work is divided between user and agent.
 */
app.get("/api/delegation", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(analyzeDelegation({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/delegation");
  }
});

/**
 * GET /api/judgment
 * Judgment analysis ΓÇö how well the user evaluates agent output.
 */
app.get("/api/judgment", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(analyzeJudgment({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/judgment");
  }
});

/**
 * GET /api/dev-plan
 * Personalized development plan with goals, quick wins, learning resources.
 */
app.get("/api/dev-plan", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(generateDevPlan({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/dev-plan");
  }
});

/**
 * GET /api/progress-check
 * Daily progress check ΓÇö today vs baseline.
 */
app.get("/api/progress-check", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(generateProgressCheck({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/progress-check");
  }
});

/**
 * GET /api/retro
 * End-of-period retrospective ΓÇö wins, misses, trends, next focus.
 */
app.get("/api/retro", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(generateRetro({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/retro");
  }
});


/**
 * GET /api/pillar-trends
 * Weekly pillar score history for trend charts.
 */
app.get("/api/pillar-trends", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(computePillarTrends({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/pillar-trends");
  }
});

/**
 * GET /api/sessions/:id/replay
 * Turn-by-turn annotated session replay with coaching signals.
 */
app.get("/api/sessions/:id/replay", (req, res) => {
  try {
    res.json(annotateSession(req.params.id));
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions/:id/replay");
  }
});

/**
 * GET /api/sessions/:id/complexity
 * Session complexity score.
 */
app.get("/api/sessions/:id/complexity", (req, res) => {
  try {
    res.json(computeSessionComplexity(req.params.id));
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions/:id/complexity");
  }
});

/**
 * GET /api/work-style
 * Work style analysis: plan vs vibe vs iterative.
 */
app.get("/api/work-style", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(analyzeWorkStyle({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/work-style");
  }
});

/**
 * GET /api/analytics/create-edit-ratio
 * Create vs edit file operation ratio.
 */
app.get("/api/analytics/create-edit-ratio", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(computeCreateEditRatio({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/create-edit-ratio");
  }
});

/**
 * GET /api/analytics/file-types
 * File type diversity / polyglot score.
 */
app.get("/api/analytics/file-types", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(computeFileTypeDiversity({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/file-types");
  }
});


// ΓöÇΓöÇ Practice Lab endpoints ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

/** Valid tag values for the challenge library. */
const VALID_LIBRARY_TAGS = new Set([
  "vague", "no-files", "no-context", "no-constraints", "no-criteria",
  "no-examples", "no-format", "no-steps", "correction", "frustration", "rollback",
]);



/**
 * POST /api/practice/analyze
 * Analyze a prompt text for quality and redirection patterns.
 * No DB access ΓÇö pure pattern matching + heuristics.
 */
app.post("/api/practice/analyze", (req, res) => {
  try {
    const { text } = req.body || {};
    if (!text || typeof text !== "string") {
      return res.status(400).json({ error: "Missing 'text' in request body" });
    }
    if (text.length > 10000) {
      return res.status(400).json({ error: "Text too long (max 10,000 characters)" });
    }
    const result = analyzePrompt(text);
    res.json(result);
  } catch (err) {
    handleRouteError(res, err, "POST /api/practice/analyze");
  }
});

/**
 * GET /api/practice/challenge
 * Fetch a random past prompt that scored poorly for the rewrite challenge.
 */
app.get("/api/practice/challenge", (req, res) => {
  try {
    const tf = req.query.timeframe || "90d";
    if (typeof tf !== "string" || !TIMEFRAME_RE.test(tf)) {
      return res.status(400).json({ error: "Invalid timeframe parameter" });
    }
    const since = parseSince(tf);
    const result = analyzeRecent({ since, limit: 200, excludeIds: hiddenSessions });

    // Collect user turns that had redirection patterns
    const candidates = [];
    for (const s of result.sessions) {
      for (const r of s.redirections) {
        if (r.weight >= 2 && r.message && r.message.length >= 20) {
          // Skip auto-generated prompts ΓÇö no coaching value
          if (isAutoGenerated(r.message)) continue;
          const analysis = analyzePrompt(r.message);
          if (analysis.score < 70) {
            candidates.push({
              originalPrompt: r.message,
              score: analysis.score,
              grade: analysis.grade,
              patterns: analysis.patterns,
              categories: analysis.categories,
              suggestions: analysis.suggestions,
              sessionId: s.session.id,
              turnIndex: r.turnIndex,
            });
          }
        }
      }
    }

    if (candidates.length === 0) {
      return res.json({
        challenge: null,
        message: "No low-scoring prompts found ΓÇö your prompting is already strong! Try the sandbox instead.",
      });
    }

    // Pick a random candidate
    const challenge = candidates[Math.floor(Math.random() * candidates.length)];
    res.json({ challenge });
  } catch (err) {
    handleRouteError(res, err, "unknown");
  }
});

/**
 * GET /api/practice/weaknesses
 * Analyze the user's recent prompts and return recommended challenge tags.
 * Scans real session turns, runs heuristics, and counts which quality signals
 * are most frequently missing ΓÇö then maps those to library tags.
 */
app.get("/api/practice/weaknesses", (req, res) => {
  try {
    const tf = req.query.timeframe || "90d";
    if (typeof tf !== "string" || !TIMEFRAME_RE.test(tf)) {
      return res.status(400).json({ error: "Invalid timeframe parameter" });
    }
    const since = parseSince(tf);
    const result = analyzeRecent({ since, limit: 200, excludeIds: hiddenSessions });

    // Aggregate heuristic gaps across all user turns
    const gaps = {
      "no-files": 0, "no-constraints": 0, "no-criteria": 0,
      "no-context": 0, "no-examples": 0, "no-format": 0,
      "no-steps": 0, vague: 0, correction: 0, frustration: 0, rollback: 0,
    };
    let totalTurns = 0;

    for (const s of result.sessions) {
      for (const r of s.redirections) {
        if (!r.message || r.message.length < 10) continue;
        // Skip auto-generated prompts
        if (isAutoGenerated(r.message)) continue;
        totalTurns++;
        const analysis = analyzePrompt(r.message);
        const h = analysis.heuristics;

        // Count missing quality signals
        if (!h.hasFilePaths && h.wordCount >= 5) gaps["no-files"]++;
        if (!h.hasConstraints && h.wordCount >= 8) gaps["no-constraints"]++;
        if (!h.hasCriteria && h.wordCount >= 10) gaps["no-criteria"]++;
        if (!h.hasContext && h.wordCount >= 10) gaps["no-context"]++;
        if (!h.hasExamples && h.wordCount >= 12) gaps["no-examples"]++;
        if (!h.hasOutputFormat && h.wordCount >= 12) gaps["no-format"]++;
        if (!h.hasSteps && h.wordCount >= 15) gaps["no-steps"]++;
        if (h.charCount < 30) gaps.vague++;

        // Count redirection categories
        for (const p of analysis.patterns) {
          if (p.category === "explicit_correction") gaps.correction++;
          else if (p.category === "frustration") gaps.frustration++;
          else if (p.category === "rollback") gaps.rollback++;
        }
      }
    }

    // Rank by frequency, return top tags with counts
    const ranked = Object.entries(gaps)
      .filter(([, count]) => count > 0)
      .sort((a, b) => b[1] - a[1])
      .map(([tag, count]) => ({ tag, count, pct: totalTurns ? Math.round((count / totalTurns) * 100) : 0 }));

    res.json({ weaknesses: ranked, totalTurns });
  } catch (err) {
    handleRouteError(res, err, "unknown");
  }
});

/**
 * GET /api/practice/library
 * Return the curated challenge library with optional tag filtering.
 * Query params:
 *   tag ΓÇö filter to prompts matching this tag (can repeat: ?tag=vague&tag=no-files)
 *   random ΓÇö if "1", return a single random prompt instead of the full list
 */
app.get("/api/practice/library", (req, res) => {
  try {
    const tags = [].concat(req.query.tag || []).filter((t) => typeof t === "string" && VALID_LIBRARY_TAGS.has(t));
    let pool = CHALLENGE_LIBRARY;
    if (tags.length > 0) {
      pool = pool.filter((c) => tags.some((t) => c.tags.includes(t)));
    }
    if (req.query.random === "1") {
      if (pool.length === 0) return res.json({ challenge: null, total: 0 });
      const pick = pool[Math.floor(Math.random() * pool.length)];
      const analysis = analyzePrompt(pick.prompt);
      return res.json({
        challenge: {
          originalPrompt: pick.prompt,
          tags: pick.tags,
          hint: pick.hint,
          score: analysis.score,
          grade: analysis.grade,
          patterns: analysis.patterns,
          categories: analysis.categories,
          suggestions: analysis.suggestions,
        },
        total: pool.length,
      });
    }
    res.json({ challenges: pool, total: pool.length });
  } catch (err) {
    handleRouteError(res, err, "GET /api/practice/library");
  }
});


// ΓöÇΓöÇ Insight generation helper ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

function generateInsights(analysisResult, topPatterns) {
  const { aggregate } = analysisResult;
  const insights = [];

  // High correction rate
  if (aggregate.avgRedirectionRate > 0.3) {
    insights.push({
      type: "warning",
      title: "High Correction Rate",
      body: `${(aggregate.avgRedirectionRate * 100).toFixed(0)}% of your turns are corrections. Try providing more upfront context ΓÇö include file paths, expected behavior, and constraints in your initial prompt.`,
      category: "general",
    });
  }

  // Explicit corrections dominate
  const corrections = aggregate.categoryTotals.explicit_correction;
  if (corrections && corrections.count > 3) {
    insights.push({
      type: "tip",
      title: "Frequent Explicit Corrections",
      body: `You're correcting the agent ${corrections.count} times across sessions. Be more specific about what you want ΓÇö include examples of the desired output or reference existing patterns in the codebase.`,
      category: "explicit_correction",
    });
  }

  // Frustration signals
  const frustration = aggregate.categoryTotals.frustration;
  if (frustration && frustration.count > 2) {
    insights.push({
      type: "warning",
      title: "Frustration Detected",
      body: `${frustration.count} frustration signals found. When the agent isn't understanding you, try breaking the task into smaller steps rather than repeating the same instruction.`,
      category: "frustration",
    });
  }

  // Course changes
  const courseChanges = aggregate.categoryTotals.course_change;
  if (courseChanges && courseChanges.count > 3) {
    insights.push({
      type: "tip",
      title: "Frequent Course Changes",
      body: `${courseChanges.count} mid-task pivots detected. Consider spending more time planning before starting ΓÇö outline the approach first, then implement. Use plan mode.`,
      category: "course_change",
    });
  }

  // Rollbacks
  const rollbacks = aggregate.categoryTotals.rollback;
  if (rollbacks && rollbacks.count > 2) {
    insights.push({
      type: "warning",
      title: "Frequent Rollback Requests",
      body: `${rollbacks.count} rollback requests across sessions. Try reviewing changes incrementally ΓÇö ask the agent to make one change at a time so you can validate before proceeding.`,
      category: "rollback",
    });
  }

  // Top pattern insight
  if (topPatterns.length > 0) {
    const top = topPatterns[0];
    insights.push({
      type: "info",
      title: `Most Common Pattern: "${top.label}"`,
      body: `This pattern appeared ${top.count} times. Example: "${top.examples[0]?.message || "N/A"}"`,
      category: top.category,
    });
  }

  // Positive feedback
  if (aggregate.avgRedirectionRate < 0.1 && aggregate.sessionsAnalyzed > 3) {
    insights.push({
      type: "success",
      title: "Great Prompting!",
      body: `Only ${(aggregate.avgRedirectionRate * 100).toFixed(0)}% redirection rate ΓÇö you're communicating clearly with the agent. Keep it up!`,
      category: "general",
    });
  }

  return insights;
}

// ΓöÇΓöÇ Live Feed ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

/**
 * GET /api/live/feed?since=<ISO>
 * Returns recent turns annotated with redirection pattern matches.
 */
app.get("/api/live/feed", (req, res) => {
  try {
    let since;
    if (req.query.since) {
      // Validate ISO 8601 date format
      const d = new Date(req.query.since);
      if (isNaN(d.getTime())) {
        return res.status(400).json({ error: "Invalid since parameter. Expected ISO 8601 date." });
      }
      since = d.toISOString();
    } else {
      since = new Date(Date.now() - 3600_000).toISOString();
    }
    const db = getDb();
    const rows = db
      .prepare(
        `SELECT t.session_id, t.turn_index, t.user_message, t.timestamp,
                s.repository, s.branch
         FROM turns t
         JOIN sessions s ON t.session_id = s.id
         WHERE t.timestamp > ?
         ORDER BY t.timestamp DESC
         LIMIT 200`
      )
      .all(since);

    const turns = rows.map((row) => {
      const patterns = matchPatterns(row.user_message);
      return {
        sessionId: row.session_id,
        turnIndex: row.turn_index,
        timestamp: row.timestamp,
        userMessage: row.user_message ? row.user_message.slice(0, 300) : "",
        repository: row.repository,
        branch: row.branch,
        patterns,
        maxWeight: patterns.reduce((max, p) => Math.max(max, p.weight), 0),
      };
    });

    res.json({ turns, serverTime: new Date().toISOString(), categories: REDIRECTION_CATEGORIES });
  } catch (err) {
    handleRouteError(res, err, "unknown");
  }
});

// ΓöÇΓöÇ Global error handler ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

app.use((err, _req, res, _next) => {
  handleRouteError(res, err, "unknown");
});

// ΓöÇΓöÇ SPA fallback ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

app.get("/{*path}", (req, res) => {
  if (req.path.startsWith("/api/")) {
    return res.status(404).json({ error: "Not found" });
  }
  res.sendFile("index.html", { root: uiDist });
});

// ΓöÇΓöÇ Start ΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇΓöÇ

const server = app.listen(PORT, "127.0.0.1", () => {
  log.info(`Copilot Insights dashboard: http://localhost:${PORT}`);
});

server.on("error", (err) => {
  if (err.code === "EADDRINUSE") {
    log.error(`Port ${PORT} is already in use. Set PORT env variable or stop the other process.`);
    process.exit(1);
  }
  throw err;
});
