// Express API server for the Copilot Insights dashboard.
// Wraps the shared analysis modules and serves data to the React frontend.

import express from "express";
import cors from "cors";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import {
  analyzeSession,
  analyzeRecent,
  findTopPatterns,
} from "../src/analyzer.mjs";
import { generateSuggestions } from "../src/suggestions.mjs";
import { analyzeSprawl } from "../src/sprawl.mjs";
import { analyzeFirstTurnClarity } from "../src/clarity.mjs";
import { analyzeEfficiency, analyzeEfficiencyBatch } from "../src/efficiency.mjs";
import {
  hourlyProductivity,
  promptLengthAnalysis,
  repoHealth,
  hotFiles,
  sessionDepth,
  toolUsage,
} from "../src/analytics.mjs";
import { analyzeInstructionGaps } from "../src/instructions.mjs";
import { analyzeInstructionFailures } from "../src/instruction-failures.mjs";
import { analyzeDelegation } from "../src/delegation.mjs";
import { analyzeJudgment } from "../src/judgment.mjs";
import { generateDevPlan, generateProgressCheck, generateRetro } from "../src/dev-plan.mjs";
import { computePillarTrends } from "../src/trends.mjs";
import { classifySessionIntent } from "../src/intent-classifier.mjs";
import { annotateSession } from "../src/replay.mjs";
import { analyzeWorkStyle } from "../src/work-style.mjs";
import { computeSessionComplexity, computeCreateEditRatio, computeFileTypeDiversity } from "../src/session-insights.mjs";
import { readVSCodeSessions, summarizeVSCodeSessions } from "../src/vscode-sessions.mjs";

import { analyzeSessionTokens, analyzeTokensBatch, computeTokenEfficiencyScore, fetchLivePricing, getLivePricingOrFallback } from "../src/tokens.mjs";
import {
  tokensByModel,
  tokensPerRedirection,
  tokensByWorkStyle,
  tokenEfficiencyMetrics,
  tokenTrends,
  budgetProjection,
  promptOptimizationTips,
} from "../src/token-analytics.mjs";

import { listSessions, getSessionTurns, getSessionRefs, getDb } from "../src/db.mjs";
import { matchPatterns, REDIRECTION_CATEGORIES } from "../src/patterns.mjs";
import { analyzePrompt } from "../src/practice.mjs";
import { isAutoGenerated } from "../src/autogenerated.mjs";
import CHALLENGE_LIBRARY from "../src/challenge-library.mjs";
import { DEFAULT_PORT } from "../src/defaults.mjs";
import { log } from "../src/log.mjs";
import { generateTips, generateImprove } from "../src/chronicle.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const app = express();
const PORT = process.env.PORT || DEFAULT_PORT;

app.use(cors({ origin: /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/ }));
app.use(express.json({ limit: "50kb" }));

// Serve static UI build in production
const uiDist = resolve(__dirname, "..", "ui", "dist");
app.use(express.static(uiDist, { etag: false, lastModified: false, setHeaders(res) { res.set("Cache-Control", "no-store"); } }));

// -- API Routes --------------------------------------------
/**
 * Convert a timeframe string (7d, 30d, 90d, all) to an ISO date.
 */
function parseSince(timeframe) {
  if (!timeframe || timeframe === "all") return undefined;
  const match = timeframe.match(/^(\d+)d$/);
  if (!match) return undefined;
  const days = parseInt(match[1]);
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}


/** Accepted timeframe patterns: digits + d/w/m/y, or "all". */
const TIMEFRAME_RE = /^(?:\d{1,4}[dwmy]|all)$/;

/**
 * Validate the `repo` query parameter — must be a non-empty string if present.
 * Returns the validated repo string or undefined.
 */
function validateRepo(req, res) {
  const repo = req.query.repo;
  if (repo === undefined || repo === "") return undefined;
  if (typeof repo !== "string") {
    res.status(400).json({ error: "Invalid 'repo' parameter — must be a string" });
    return null;
  }
  return repo;
}

/**
 * Validate and parse the `timeframe` query parameter.
 * Returns the ISO date string, undefined (for "all"), or null on validation failure.
 */
function validateTimeframe(req, res) {
  const tf = req.query.timeframe;
  if (!tf || tf === "all") return undefined;
  if (typeof tf !== "string" || !TIMEFRAME_RE.test(tf)) {
    res.status(400).json({ error: "Invalid 'timeframe' parameter — use format like '7d', '30d', or 'all'" });
    return null;
  }
  return parseSince(tf);
}

/**
 * Validate a direct ISO `since` query parameter.
 */
function validateSince(req, res) {
  const since = req.query.since;
  if (since === undefined || since === "") return undefined;
  if (typeof since !== "string") {
    res.status(400).json({ error: "Invalid 'since' parameter — must be an ISO date string" });
    return null;
  }
  const parsed = new Date(since);
  if (Number.isNaN(parsed.getTime())) {
    res.status(400).json({ error: "Invalid 'since' parameter — must be an ISO date string" });
    return null;
  }
  return parsed.toISOString();
}

/**
 * Build a standard { repo, since, excludeIds } filter object for analytics routes.
 */
function buildFilterOpts(req, res) {
  const repo = validateRepo(req, res);
  if (repo === null) return null;

  const since = req.query.since !== undefined
    ? validateSince(req, res)
    : validateTimeframe(req, res);
  if (since === null) return null;

  const excludeIds = new Set(hiddenSessions);
  if (req.query.excludeIds !== undefined && req.query.excludeIds !== "") {
    if (typeof req.query.excludeIds !== "string") {
      res.status(400).json({ error: "Invalid 'excludeIds' parameter — must be a comma-separated string" });
      return null;
    }
    for (const id of req.query.excludeIds.split(",").map((value) => value.trim()).filter(Boolean)) {
      excludeIds.add(id);
    }
  }

  return { repo, since, excludeIds };
}

function parseTimeframeQuery(query) {
  const repo = typeof query.repo === "string" && query.repo !== "" ? query.repo : undefined;
  if (typeof query.since === "string" && query.since !== "") {
    const parsed = new Date(query.since);
    return {
      repo,
      since: Number.isNaN(parsed.getTime()) ? undefined : parsed.toISOString(),
    };
  }
  if (typeof query.timeframe === "string" && query.timeframe !== "" && query.timeframe !== "all") {
    return { repo, since: parseSince(query.timeframe) };
  }
  return { repo, since: undefined };
}

/**
 * Standardized route error handler — logs context and sends user-friendly 500.
 */
function handleRouteError(res, err, route) {
  log.error(`[${route}]`, err);

  // Surface actionable DB errors to the user
  if (err.message?.includes("session database") || err.message?.includes("Session store") || err.message?.includes("SQLITE")) {
    return res.status(500).json({
      error: "Couldn't access the Copilot session database. Make sure Copilot CLI is installed and you've completed at least one session.",
    });
  }

  res.status(500).json({ error: "Something went wrong — check the server logs for details." });
}
// -- Session Hiding (persisted to disk) ---------------------- 

const HIDDEN_FILE = join(homedir(), ".copilot", "copilot-insights-hidden.json");
const MAX_HIDDEN = 5000;
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function loadHiddenSessions() {
  try {
    const raw = readFileSync(HIDDEN_FILE, "utf-8");
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) {
      const valid = parsed.filter((id) => typeof id === "string" && UUID_RE.test(id));
      return new Set(valid.slice(0, MAX_HIDDEN));
    }
  } catch {
    // File missing, corrupted, or unreadable — start fresh
  }
  return new Set();
}

function saveHiddenSessions(set) {
  try {
    mkdirSync(join(homedir(), ".copilot"), { recursive: true });
    writeFileSync(HIDDEN_FILE, JSON.stringify([...set]), "utf-8");
  } catch (err) {
    log.error("[hidden-sessions] Failed to save:", err.message);
  }
}

const hiddenSessions = loadHiddenSessions();

// -- Session Intent Tags (persisted to disk) ----------------------
const TAGS_FILE = join(homedir(), ".copilot", "copilot-insights-tags.json");

// Valid intent tags
const VALID_INTENTS = new Set(["build", "explore", "iterate", "debug"]);

function loadSessionTags() {
  try {
    const raw = readFileSync(TAGS_FILE, "utf-8");
    const parsed = JSON.parse(raw);
    if (typeof parsed === "object" && !Array.isArray(parsed)) {
      // Validate entries
      const clean = {};
      for (const [id, tag] of Object.entries(parsed)) {
        if (UUID_RE.test(id) && VALID_INTENTS.has(tag)) {
          clean[id] = tag;
        }
      }
      return clean;
    }
  } catch {
    // File missing or corrupted — start fresh
  }
  return {};
}

function saveSessionTags(tags) {
  try {
    mkdirSync(join(homedir(), ".copilot"), { recursive: true });
    writeFileSync(TAGS_FILE, JSON.stringify(tags, null, 2), "utf-8");
  } catch (err) {
    log.error("[session-tags] Failed to save:", err.message);
  }
}

const sessionTags = loadSessionTags();

/**
 * GET /api/hidden-sessions
 * Return list of session IDs currently hidden from analysis.
 * Hidden sessions are persisted to ~/.copilot/copilot-insights-hidden.json.
 */
app.get("/api/hidden-sessions", (_req, res) => {
  res.json({ sessionIds: [...hiddenSessions] });
});

/**
 * POST /api/sessions/:id/hide
 * Add a session ID to the hidden set and persist to disk.
 * Returns 400 if ID is not a valid UUID v4, 429 if cap reached.
 */
app.post("/api/sessions/:id/hide", (req, res) => {
  const { id } = req.params;
  if (!UUID_RE.test(id)) {
    return res.status(400).json({ error: "Invalid session ID format" });
  }
  if (hiddenSessions.size >= MAX_HIDDEN && !hiddenSessions.has(id)) {
    return res.status(429).json({ error: "Hidden sessions limit reached" });
  }
  hiddenSessions.add(id);
  saveHiddenSessions(hiddenSessions);
  res.json({ ok: true });
});

/**
 * DELETE /api/sessions/:id/hide
 * Remove a session ID from the hidden set and persist to disk.
 * Returns 400 if ID is not a valid UUID v4.
 */
app.delete("/api/sessions/:id/hide", (req, res) => {
  const { id } = req.params;
  if (!UUID_RE.test(id)) {
    return res.status(400).json({ error: "Invalid session ID format" });
  }
  hiddenSessions.delete(id);
  saveHiddenSessions(hiddenSessions);
  res.json({ ok: true });
});

// -- Session Intent Tags API ----------------------------------------

/**
 * GET /api/sessions/:id/intent
 * Get the intent tag for a session.
 */
app.get("/api/sessions/:id/intent", (req, res) => {
  const { id } = req.params;
  if (!UUID_RE.test(id)) {
    return res.status(400).json({ error: "Invalid session ID format" });
  }
  res.json({ intent: sessionTags[id] || null });
});

/**
 * PUT /api/sessions/:id/intent
 * Set the intent tag for a session.
 * Body: { "intent": "build" | "explore" | "iterate" | "debug" }
 */
app.put("/api/sessions/:id/intent", (req, res) => {
  const { id } = req.params;
  if (!UUID_RE.test(id)) {
    return res.status(400).json({ error: "Invalid session ID format" });
  }
  const { intent } = req.body;
  if (!intent) {
    delete sessionTags[id];
    saveSessionTags(sessionTags);
    return res.json({ ok: true, intent: null });
  }
  if (!VALID_INTENTS.has(intent)) {
    return res.status(400).json({ error: `Invalid intent. Must be one of: ${[...VALID_INTENTS].join(", ")}` });
  }
  sessionTags[id] = intent;
  saveSessionTags(sessionTags);
  res.json({ ok: true, intent });
});

/**
 * GET /api/session-intents
 * Get all session intent tags (for bulk operations).
 */
app.get("/api/session-intents", (_req, res) => {
  res.json({ intents: { ...sessionTags } });
});

/**
 * GET /api/sessions/:id/intent-suggestion
 * Auto-detect the intent for a session based on content analysis.
 */
app.get("/api/sessions/:id/intent-suggestion", (req, res) => {
  try {
    if (!UUID_RE.test(req.params.id)) {
      return res.status(400).json({ error: "Invalid session ID format" });
    }
    const result = classifySessionIntent(req.params.id);
    res.json(result);
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions/:id/intent-suggestion");
  }
});

// ── Dev Plan Goals ──────────────────────────────────────────
const DEVPLAN_FILE = join(homedir(), ".copilot", "copilot-insights-devplan.json");
const JOURNAL_FILE = join(homedir(), ".copilot", "copilot-insights-journal.md");

function readDevPlan() {
  try {
    if (!existsSync(DEVPLAN_FILE)) return { goals: [] };
    const parsed = JSON.parse(readFileSync(DEVPLAN_FILE, "utf-8"));
    if (!parsed || typeof parsed !== "object" || !Array.isArray(parsed.goals)) return { goals: [] };
    return parsed;
  } catch {
    return { goals: [] };
  }
}

function writeDevPlan(data) {
  const dir = dirname(DEVPLAN_FILE);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(DEVPLAN_FILE, JSON.stringify(data, null, 2), "utf-8");
  regenerateJournal(data);
}

function regenerateJournal(plan) {
  const lines = [
    "# Copilot Insights — Development Journal",
    "",
    `_Last updated: ${new Date().toISOString()}_`,
    "",
  ];

  const active = plan.goals.filter((g) => g.status === "active");
  const sufficient = plan.goals.filter((g) => g.status === "sufficient");

  if (active.length > 0) {
    lines.push("## 🎯 Active Goals", "");
    for (const g of active) {
      lines.push(`### ${g.title}`);
      lines.push(`- **Pillar:** ${g.pillar}`);
      lines.push(`- **Added:** ${new Date(g.addedAt).toLocaleDateString()}`);
      if (g.baselineScore !== null && g.baselineScore !== undefined) lines.push(`- **Baseline Score:** ${g.baselineScore}`);
      if (g.latestScore !== null && g.latestScore !== undefined) lines.push(`- **Latest Score:** ${g.latestScore}`);
      if (g.description) lines.push(`- **Details:** ${g.description}`);
      if (g.notes && g.notes.length > 0) {
        lines.push("", "**Notes & Insights:**");
        for (const n of g.notes) {
          lines.push(`- _${new Date(n.createdAt).toLocaleDateString()}:_ ${n.text}`);
        }
      }
      lines.push("");
    }
  }

  if (sufficient.length > 0) {
    lines.push("## ✅ Development Sufficient", "");
    for (const g of sufficient) {
      lines.push(`### ${g.title}`);
      lines.push(`- **Pillar:** ${g.pillar}`);
      if (
        g.baselineScore !== null && g.baselineScore !== undefined
        && g.latestScore !== null && g.latestScore !== undefined
      ) {
        lines.push(`- **Progress:** ${g.baselineScore} → ${g.latestScore}`);
      }
      if (g.completedAt) lines.push(`- **Completed:** ${new Date(g.completedAt).toLocaleDateString()}`);
      if (g.notes && g.notes.length > 0) {
        lines.push("", "**Notes & Insights:**");
        for (const n of g.notes) {
          lines.push(`- _${new Date(n.createdAt).toLocaleDateString()}:_ ${n.text}`);
        }
      }
      lines.push("");
    }
  }

  if (active.length === 0 && sufficient.length === 0) {
    lines.push("_No development goals yet. Add tips from the Skill Building page._", "");
  }

  lines.push("---", "", "_Auto-generated by Copilot Insights. Edit goals from the dashboard._", "");

  try {
    const dir = dirname(JOURNAL_FILE);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(JOURNAL_FILE, lines.join("\n"), "utf-8");
  } catch (err) {
    console.error("[journal] Failed to write journal:", err.message);
  }
}

// GET /api/devplan/goals — list all goals
app.get("/api/devplan/goals", (req, res) => {
  try {
    const plan = readDevPlan();
    const includeProgress = req.query.progress === "true";
    if (includeProgress) {
      const { since, repo } = parseTimeframeQuery(req.query);
      const devPlan = generateDevPlan({ repo, since, excludeIds: hiddenSessions, sessionIntents: sessionTags });
      const currentScores = devPlan.pillarScores || {};
      const SCORE_MAP = {
        delegation: "workDesign",
        judgment: "qualityControl",
        specification: "intent",
        efficiency: "evaluation",
        workDesign: "workDesign",
        qualityControl: "qualityControl",
        intent: "intent",
        evaluation: "evaluation",
      };
      const normalizedScores = {};
      for (const [key, value] of Object.entries(currentScores)) {
        normalizedScores[SCORE_MAP[key] || key] = value;
      }
      for (const goal of plan.goals) {
        if (goal.status === "active" && normalizedScores[goal.pillar] !== null && normalizedScores[goal.pillar] !== undefined) {
          goal.latestScore = normalizedScores[goal.pillar];
          goal.lastChecked = new Date().toISOString();
        }
      }
    }
    res.json(plan);
  } catch (err) {
    handleRouteError(res, err, "GET /api/devplan/goals");
  }
});

app.get("/api/devplan/journal", (req, res) => {
  try {
    if (!existsSync(JOURNAL_FILE)) {
      // Generate from existing goals (covers goals added before journal feature)
      const plan = readDevPlan();
      if (plan.goals.length > 0) {
        regenerateJournal(plan);
      }
    }
    if (!existsSync(JOURNAL_FILE)) {
      return res.type("text/markdown").send("# Copilot Insights — Development Journal\n\n_No goals yet._\n");
    }
    res.type("text/markdown").send(readFileSync(JOURNAL_FILE, "utf-8"));
  } catch (err) {
    handleRouteError(res, err, "GET /api/devplan/journal");
  }
});

// POST /api/devplan/goals — add a new goal
app.post("/api/devplan/goals", (req, res) => {
  try {
    const { pillar, title, description, source, baselineScore } = req.body;
    if (!pillar || !title) return res.status(400).json({ error: "pillar and title required" });
    const plan = readDevPlan();
    const exists = plan.goals.some((goal) => goal.title === title && goal.pillar === pillar && goal.status === "active");
    if (exists) return res.status(409).json({ error: "Goal already exists" });
    const goal = {
      id: `goal-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
      pillar,
      title,
      description: description || "",
      source: source || "manual",
      addedAt: new Date().toISOString(),
      baselineScore: baselineScore ?? null,
      latestScore: null,
      lastChecked: null,
      status: "active",
      notes: [],
    };
    plan.goals.push(goal);
    writeDevPlan(plan);
    res.status(201).json(goal);
  } catch (err) {
    handleRouteError(res, err, "POST /api/devplan/goals");
  }
});

// PATCH /api/devplan/goals/:id — update goal status
app.patch("/api/devplan/goals/:id", (req, res) => {
  try {
    const { status, addNote } = req.body;
    const plan = readDevPlan();
    const goal = plan.goals.find((item) => item.id === req.params.id);
    if (!goal) return res.status(404).json({ error: "Goal not found" });

    if (status) {
      if (!["active", "sufficient", "removed"].includes(status)) {
        return res.status(400).json({ error: "status must be active, sufficient, or removed" });
      }
      goal.status = status;
      if (status === "sufficient") goal.completedAt = new Date().toISOString();
    }

    if (addNote && typeof addNote === "string" && addNote.trim()) {
      if (!Array.isArray(goal.notes)) goal.notes = [];
      goal.notes.push({
        text: addNote.trim(),
        createdAt: new Date().toISOString(),
      });
    }

    writeDevPlan(plan);
    res.json(goal);
  } catch (err) {
    handleRouteError(res, err, "PATCH /api/devplan/goals/:id");
  }
});

// DELETE /api/devplan/goals/:id — permanently delete a goal
app.delete("/api/devplan/goals/:id", (req, res) => {
  try {
    const plan = readDevPlan();
    const index = plan.goals.findIndex((goal) => goal.id === req.params.id);
    if (index === -1) return res.status(404).json({ error: "Goal not found" });
    plan.goals.splice(index, 1);
    writeDevPlan(plan);
    res.json({ ok: true });
  } catch (err) {
    handleRouteError(res, err, "DELETE /api/devplan/goals/:id");
  }
});

/**
 * GET /api/summary
 * Aggregate redirection stats across recent sessions.
 */
app.get("/api/summary", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const result = analyzeRecent({ repo, since, excludeIds: hiddenSessions });
    res.json(result.aggregate);
  } catch (err) {
    handleRouteError(res, err, "GET /api/summary");
  }
});

/**
 * GET /api/sessions
 * List sessions with redirection scores, ranked by severity.
 */
app.get("/api/sessions", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const result = analyzeRecent({ repo, since, excludeIds: hiddenSessions });

    const sessions = result.sessions.map((s) => ({
      id: s.session.id,
      repository: s.session.repository,
      branch: s.session.branch,
      summary: s.session.summary,
      createdAt: s.session.createdAt,
      turnCount: s.session.turnCount,
      redirectionCount: s.stats.totalRedirections,
      redirectionRate: s.stats.redirectionRate,
      totalWeight: s.stats.totalWeight,
      thrashedFileCount: s.stats.thrashedFileCount,
      categoryBreakdown: s.categoryBreakdown,
    }));

    res.json({ sessions, aggregate: result.aggregate });
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions");
  }
});

/**
 * GET /api/sessions/:id
 * Detailed analysis of a single session.
 */
app.get("/api/sessions/:id", (req, res) => {
  try {
    const report = analyzeSession(req.params.id);
    if (!report) {
      return res.status(404).json({ error: "Session not found" });
    }
    res.json(report);
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions/:id");
  }
});

/**
 * GET /api/patterns
 * Top redirection patterns across sessions.
 */
app.get("/api/patterns", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const patterns = findTopPatterns({ repo, since, excludeIds: hiddenSessions });
    res.json({ patterns });
  } catch (err) {
    handleRouteError(res, err, "GET /api/patterns");
  }
});

// Simple time-based cache for VS Code session reads (avoids re-walking dirs + opening SQLite DBs per request)
let vscodeCacheData = null;
let vscodeCacheTime = 0;
const VSCODE_CACHE_TTL = 30_000; // 30 seconds

function getCachedVSCodeSessions() {
  if (vscodeCacheData && Date.now() - vscodeCacheTime < VSCODE_CACHE_TTL) return vscodeCacheData;
  vscodeCacheData = readVSCodeSessions();
  vscodeCacheTime = Date.now();
  return vscodeCacheData;
}

/**
 * GET /api/vscode/sessions
 * List Copilot Chat histories read from VS Code workspace storage.
 */
app.get("/api/vscode/sessions", (_req, res) => {
  try {
    res.json(getCachedVSCodeSessions());
  } catch (err) {
    handleRouteError(res, err, "GET /api/vscode/sessions");
  }
});

/**
 * GET /api/vscode/sessions/:workspaceId
 * Return a single VS Code workspace session by workspace hash.
 */
app.get("/api/vscode/sessions/:workspaceId", (req, res) => {
  try {
    const session = getCachedVSCodeSessions().find((item) => item.workspaceId === req.params.workspaceId);
    if (!session) {
      return res.status(404).json({ error: "VS Code workspace session not found" });
    }
    res.json(session);
  } catch (err) {
    handleRouteError(res, err, "GET /api/vscode/sessions/:workspaceId");
  }
});

/**
 * GET /api/vscode/summary
 * Aggregate VS Code Copilot Chat stats across workspaces.
 */
app.get("/api/vscode/summary", (_req, res) => {
  try {
    res.json(summarizeVSCodeSessions(getCachedVSCodeSessions()));
  } catch (err) {
    handleRouteError(res, err, "GET /api/vscode/summary");
  }
});

/**
 * GET /api/trends
 * Redirection rates bucketed by date for trend charting.
 */
app.get("/api/trends", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const result = analyzeRecent({ repo, since, excludeIds: hiddenSessions });

    // Bucket sessions by date
    const buckets = {};
    for (const s of result.sessions) {
      const date = s.session.createdAt?.split("T")[0] || "unknown";
      if (!buckets[date]) {
        buckets[date] = {
          date,
          sessionCount: 0,
          totalRedirections: 0,
          totalTurns: 0,
          totalWeight: 0,
        };
      }
      buckets[date].sessionCount++;
      buckets[date].totalRedirections += s.stats.totalRedirections;
      buckets[date].totalTurns += s.stats.userTurnCount;
      buckets[date].totalWeight += s.stats.totalWeight;
    }

    const trends = Object.values(buckets)
      .map((b) => ({
        ...b,
        redirectionRate:
          b.totalTurns > 0 ? b.totalRedirections / b.totalTurns : 0,
      }))
      .sort((a, b) => a.date.localeCompare(b.date));

    res.json({ trends });
  } catch (err) {
    handleRouteError(res, err, "unknown");
  }
});

/**
 * GET /api/insights
 * Actionable prompting tips derived from redirection data.
 */
app.get("/api/insights", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const result = analyzeRecent({ repo, since, excludeIds: hiddenSessions });
    const patterns = findTopPatterns({ repo, since, excludeIds: hiddenSessions });

    const insights = generateInsights(result, patterns);
    res.json({ insights });
  } catch (err) {
    handleRouteError(res, err, "GET /api/insights");
  }
});

/**
 * GET /api/suggestions
 * Prompt rewrite suggestions based on actual redirections.
 */
app.get("/api/suggestions", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const data = generateSuggestions({ repo, since, excludeIds: hiddenSessions });
    res.json({ suggestions: data });
  } catch (err) {
    handleRouteError(res, err, "GET /api/suggestions");
  }
});

// -- Insight Generation ------------------------------------
/**
 * GET /api/sessions/:id/sprawl
 * Sprawl analysis for a single session.
 */
app.get("/api/sessions/:id/sprawl", (req, res) => {
  try {
    const result = analyzeSprawl(req.params.id);
    if (!result) return res.json({ sprawl: null, message: "Session too short to analyze" });
    res.json(result);
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions/:id/sprawl");
  }
});

/**
 * GET /api/sessions/:id/efficiency
 * Efficiency analysis for a single session.
 */
app.get("/api/sessions/:id/efficiency", (req, res) => {
  try {
    const turns = getSessionTurns(req.params.id);
    const refs = getSessionRefs(req.params.id);
    const result = analyzeEfficiency(turns, refs);
    if (!result) return res.json({ efficiency: null, message: "Session too short to analyze" });
    res.json(result);
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions/:id/efficiency");
  }
});

/**
 * GET /api/clarity
 * First-turn clarity analysis across sessions.
 */
app.get("/api/clarity", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const sessions = listSessions({ repo, since, excludeIds: hiddenSessions });
    const result = analyzeFirstTurnClarity(
      sessions.filter((s) => s.turn_count >= 2),
      getSessionTurns
    );
    res.json(result);
  } catch (err) {
    handleRouteError(res, err, "GET /api/clarity");
  }
});

/**
 * GET /api/efficiency
 * Turn efficiency analysis across sessions.
 */
app.get("/api/efficiency", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const sessions = listSessions({ repo, since, excludeIds: hiddenSessions });
    const sessionsData = sessions
      .filter((s) => s.turn_count >= 2)
      .map((s) => ({
        session: s,
        turns: getSessionTurns(s.id),
        refs: getSessionRefs(s.id),
      }));
    const result = analyzeEfficiencyBatch(sessionsData);
    res.json(result);
  } catch (err) {
    handleRouteError(res, err, "GET /api/efficiency");
  }
});

// -- Analytics endpoints -----------------------------------
/**
 * GET /api/analytics/hourly
 * Turns and redirection rate by hour of day.
 */
app.get("/api/analytics/hourly", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(hourlyProductivity({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/hourly");
  }
});

/**
 * GET /api/analytics/prompt-length
 * Redirection rate by prompt length bucket.
 */
app.get("/api/analytics/prompt-length", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(promptLengthAnalysis({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/prompt-length");
  }
});

/**
 * GET /api/analytics/repos
 * Per-repo session counts and redirection rates.
 */
app.get("/api/analytics/repos", (req, res) => {
  try {
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(repoHealth({ since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/repos");
  }
});

/**
 * GET /api/analytics/hot-files
 * Most-touched files across sessions.
 */
app.get("/api/analytics/hot-files", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(hotFiles({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/hot-files");
  }
});

/**
 * GET /api/analytics/depth
 * Session depth distribution.
 */
app.get("/api/analytics/depth", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(sessionDepth({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/depth");
  }
});

/**
 * GET /api/analytics/tools
 * Tool usage breakdown (create vs edit).
 */
app.get("/api/analytics/tools", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(toolUsage({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/tools");
  }
});

/**
 * GET /api/instruction-gaps
 * Instruction file gap analysis — repeated conventions that should be codified.
 */
app.get("/api/instruction-gaps", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(analyzeInstructionGaps({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/instruction-gaps");
  }
});

/**
 * GET /api/instruction-failures
 * Instruction failure analysis — rules that exist but agent ignores/forgets.
 */
app.get("/api/instruction-failures", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(analyzeInstructionFailures({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/instruction-failures");
  }
});

/**
 * GET /api/delegation
 * Delegation analysis — how work is divided between user and agent.
 */
app.get("/api/delegation", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(analyzeDelegation({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/delegation");
  }
});

/**
 * GET /api/judgment
 * Judgment analysis — how well the user evaluates agent output.
 */
app.get("/api/judgment", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(analyzeJudgment({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/judgment");
  }
});

/**
 * GET /api/dev-plan
 * Personalized development plan with goals, quick wins, learning resources.
 */
app.get("/api/dev-plan", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(generateDevPlan({ repo, since, excludeIds: hiddenSessions, sessionIntents: sessionTags }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/dev-plan");
  }
});

/**
 * GET /api/progress-check
 * Daily progress check — today vs baseline.
 */
app.get("/api/progress-check", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(generateProgressCheck({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/progress-check");
  }
});

/**
 * GET /api/retro
 * End-of-period retrospective — wins, misses, trends, next focus.
 */
app.get("/api/retro", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(generateRetro({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/retro");
  }
});


/**
 * GET /api/pillar-trends
 * Weekly pillar score history for trend charts.
 */
app.get("/api/pillar-trends", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(computePillarTrends({ repo, since, excludeIds: hiddenSessions, sessionIntents: sessionTags }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/pillar-trends");
  }
});

/**
 * GET /api/sessions/:id/replay
 * Turn-by-turn annotated session replay with coaching signals.
 */
app.get("/api/sessions/:id/replay", (req, res) => {
  try {
    res.json(annotateSession(req.params.id));
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions/:id/replay");
  }
});

/**
 * GET /api/sessions/:id/complexity
 * Session complexity score.
 */
app.get("/api/sessions/:id/complexity", (req, res) => {
  try {
    res.json(computeSessionComplexity(req.params.id));
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions/:id/complexity");
  }
});

/**
 * GET /api/work-style
 * Work style analysis: plan vs vibe vs iterative.
 */
app.get("/api/work-style", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(analyzeWorkStyle({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/work-style");
  }
});

/**
 * GET /api/analytics/create-edit-ratio
 * Create vs edit file operation ratio.
 */
app.get("/api/analytics/create-edit-ratio", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(computeCreateEditRatio({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/create-edit-ratio");
  }
});

/**
 * GET /api/analytics/file-types
 * File type diversity / polyglot score.
 */
app.get("/api/analytics/file-types", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(computeFileTypeDiversity({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/analytics/file-types");
  }
});


// -- Practice Lab endpoints --------------------------------
/** Valid tag values for the challenge library. */
const VALID_LIBRARY_TAGS = new Set([
  "vague", "no-files", "no-context", "no-constraints", "no-criteria",
  "no-examples", "no-format", "no-steps", "correction", "frustration", "rollback",
]);



/**
 * POST /api/practice/analyze
 * Analyze a prompt text for quality and redirection patterns.
 * No DB access — pure pattern matching + heuristics.
 */
app.post("/api/practice/analyze", (req, res) => {
  try {
    const { text } = req.body || {};
    if (!text || typeof text !== "string") {
      return res.status(400).json({ error: "Missing 'text' in request body" });
    }
    if (text.length > 10000) {
      return res.status(400).json({ error: "Text too long (max 10,000 characters)" });
    }
    const result = analyzePrompt(text);
    res.json(result);
  } catch (err) {
    handleRouteError(res, err, "POST /api/practice/analyze");
  }
});

/**
 * GET /api/practice/challenge
 * Fetch a random past prompt that scored poorly for the rewrite challenge.
 */
app.get("/api/practice/challenge", (req, res) => {
  try {
    const tf = req.query.timeframe || "90d";
    if (typeof tf !== "string" || !TIMEFRAME_RE.test(tf)) {
      return res.status(400).json({ error: "Invalid timeframe parameter" });
    }
    const since = parseSince(tf);
    const result = analyzeRecent({ since, limit: 200, excludeIds: hiddenSessions });

    // Collect user turns that had redirection patterns
    const candidates = [];
    for (const s of result.sessions) {
      for (const r of s.redirections) {
        if (r.weight >= 2 && r.message && r.message.length >= 20) {
          // Skip auto-generated prompts — no coaching value
          if (isAutoGenerated(r.message)) continue;
          const analysis = analyzePrompt(r.message);
          if (analysis.score < 70) {
            candidates.push({
              originalPrompt: r.message,
              score: analysis.score,
              grade: analysis.grade,
              patterns: analysis.patterns,
              categories: analysis.categories,
              suggestions: analysis.suggestions,
              heuristics: analysis.heuristics,
              sessionId: s.session.id,
              turnIndex: r.turnIndex,
            });
          }
        }
      }
    }

    if (candidates.length === 0) {
      return res.json({
        challenge: null,
        message: "No low-scoring prompts found — your prompting is already strong! Try the sandbox instead.",
      });
    }

    // Pick a random candidate
    const challenge = candidates[Math.floor(Math.random() * candidates.length)];
    res.json({ challenge });
  } catch (err) {
    handleRouteError(res, err, "unknown");
  }
});

/**
 * GET /api/practice/weaknesses
 * Analyze the user's recent prompts and return recommended challenge tags.
 * Scans real session turns, runs heuristics, and counts which quality signals
 * are most frequently missing — then maps those to library tags.
 */
app.get("/api/practice/weaknesses", (req, res) => {
  try {
    const tf = req.query.timeframe || "90d";
    if (typeof tf !== "string" || !TIMEFRAME_RE.test(tf)) {
      return res.status(400).json({ error: "Invalid timeframe parameter" });
    }
    const since = parseSince(tf);
    const result = analyzeRecent({ since, limit: 200, excludeIds: hiddenSessions });

    // Aggregate heuristic gaps across all user turns
    const gaps = {
      "no-files": 0, "no-constraints": 0, "no-criteria": 0,
      "no-context": 0, "no-examples": 0, "no-format": 0,
      "no-steps": 0, vague: 0, correction: 0, frustration: 0, rollback: 0,
    };
    let totalTurns = 0;

    for (const s of result.sessions) {
      for (const r of s.redirections) {
        if (!r.message || r.message.length < 10) continue;
        // Skip auto-generated prompts
        if (isAutoGenerated(r.message)) continue;
        totalTurns++;
        const analysis = analyzePrompt(r.message);
        const h = analysis.heuristics;

        // Count missing quality signals
        if (!h.hasFilePaths && h.wordCount >= 5) gaps["no-files"]++;
        if (!h.hasConstraints && h.wordCount >= 8) gaps["no-constraints"]++;
        if (!h.hasCriteria && h.wordCount >= 10) gaps["no-criteria"]++;
        if (!h.hasContext && h.wordCount >= 10) gaps["no-context"]++;
        if (!h.hasExamples && h.wordCount >= 12) gaps["no-examples"]++;
        if (!h.hasOutputFormat && h.wordCount >= 12) gaps["no-format"]++;
        if (!h.hasSteps && h.wordCount >= 15) gaps["no-steps"]++;
        if (h.charCount < 30) gaps.vague++;

        // Count redirection categories
        for (const p of analysis.patterns) {
          if (p.category === "explicit_correction") gaps.correction++;
          else if (p.category === "frustration") gaps.frustration++;
          else if (p.category === "rollback") gaps.rollback++;
        }
      }
    }

    // Rank by frequency, return top tags with counts
    const ranked = Object.entries(gaps)
      .filter(([, count]) => count > 0)
      .sort((a, b) => b[1] - a[1])
      .map(([tag, count]) => ({ tag, count, pct: totalTurns ? Math.round((count / totalTurns) * 100) : 0 }));

    res.json({ weaknesses: ranked, totalTurns });
  } catch (err) {
    handleRouteError(res, err, "unknown");
  }
});

/**
 * GET /api/practice/library
 * Return the curated challenge library with optional tag filtering.
 * Query params:
 *   tag — filter to prompts matching this tag (can repeat: ?tag=vague&tag=no-files)
 *   random — if "1", return a single random prompt instead of the full list
 */
app.get("/api/practice/library", (req, res) => {
  try {
    const tags = [].concat(req.query.tag || []).filter((t) => typeof t === "string" && VALID_LIBRARY_TAGS.has(t));
    let pool = CHALLENGE_LIBRARY;
    if (tags.length > 0) {
      pool = pool.filter((c) => tags.some((t) => c.tags.includes(t)));
    }
    if (req.query.random === "1") {
      if (pool.length === 0) return res.json({ challenge: null, total: 0 });
      const pick = pool[Math.floor(Math.random() * pool.length)];
      const analysis = analyzePrompt(pick.prompt);
      return res.json({
        challenge: {
          originalPrompt: pick.prompt,
          tags: pick.tags,
          hint: pick.hint,
          score: analysis.score,
          grade: analysis.grade,
          patterns: analysis.patterns,
          categories: analysis.categories,
          suggestions: analysis.suggestions,
          heuristics: analysis.heuristics,
        },
        total: pool.length,
      });
    }
    res.json({ challenges: pool, total: pool.length });
  } catch (err) {
    handleRouteError(res, err, "GET /api/practice/library");
  }
});


// -- Insight generation helper -----------------------------
function generateInsights(analysisResult, topPatterns) {
  const { aggregate } = analysisResult;
  const insights = [];

  // High correction rate
  if (aggregate.avgRedirectionRate > 0.3) {
    insights.push({
      type: "warning",
      title: "High Correction Rate",
      body: `${(aggregate.avgRedirectionRate * 100).toFixed(0)}% of your turns are corrections. Try providing more upfront context — include file paths, expected behavior, and constraints in your initial prompt.`,
      category: "general",
    });
  }

  // Explicit corrections dominate
  const corrections = aggregate.categoryTotals.explicit_correction;
  if (corrections && corrections.count > 3) {
    insights.push({
      type: "tip",
      title: "Frequent Explicit Corrections",
      body: `You're correcting the agent ${corrections.count} times across sessions. Be more specific about what you want — include examples of the desired output or reference existing patterns in the codebase.`,
      category: "explicit_correction",
    });
  }

  // Frustration signals
  const frustration = aggregate.categoryTotals.frustration;
  if (frustration && frustration.count > 2) {
    insights.push({
      type: "warning",
      title: "Frustration Detected",
      body: `${frustration.count} frustration signals found. When the agent isn't understanding you, try breaking the task into smaller steps rather than repeating the same instruction.`,
      category: "frustration",
    });
  }

  // Course changes
  const courseChanges = aggregate.categoryTotals.course_change;
  if (courseChanges && courseChanges.count > 3) {
    insights.push({
      type: "tip",
      title: "Frequent Course Changes",
      body: `${courseChanges.count} mid-task pivots detected. Consider spending more time planning before starting — outline the approach first, then implement. Use plan mode.`,
      category: "course_change",
    });
  }

  // Rollbacks
  const rollbacks = aggregate.categoryTotals.rollback;
  if (rollbacks && rollbacks.count > 2) {
    insights.push({
      type: "warning",
      title: "Frequent Rollback Requests",
      body: `${rollbacks.count} rollback requests across sessions. Try reviewing changes incrementally — ask the agent to make one change at a time so you can validate before proceeding.`,
      category: "rollback",
    });
  }

  // Top pattern insight
  if (topPatterns.length > 0) {
    const top = topPatterns[0];
    insights.push({
      type: "info",
      title: `Most Common Pattern: "${top.label}"`,
      body: `This pattern appeared ${top.count} times. Example: "${top.examples[0]?.message || "N/A"}"`,
      category: top.category,
    });
  }

  // Positive feedback
  if (aggregate.avgRedirectionRate < 0.1 && aggregate.sessionsAnalyzed > 3) {
    insights.push({
      type: "success",
      title: "Great Prompting!",
      body: `Only ${(aggregate.avgRedirectionRate * 100).toFixed(0)}% redirection rate — you're communicating clearly with the agent. Keep it up!`,
      category: "general",
    });
  }

  return insights;
}

// -- Token Usage & Cost endpoints ---------------------------

/**
 * GET /api/tokens/pricing
 * Live pricing from GitHub Copilot docs (cached 1h), falls back to hardcoded.
 */
app.get("/api/tokens/pricing", async (req, res) => {
  try {
    await fetchLivePricing(); // populate cache if stale
    res.json(getLivePricingOrFallback());
  } catch (err) {
    handleRouteError(res, err, "GET /api/tokens/pricing");
  }
});

/**
 * GET /api/tokens/summary
 * Aggregate token usage: total in/out, by model, estimated cost.
 */
app.get("/api/tokens/summary", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(analyzeTokensBatch({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/tokens/summary");
  }
});

/**
 * GET /api/tokens/by-model
 * Per-model token breakdown with costs.
 */
app.get("/api/tokens/by-model", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(tokensByModel({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/tokens/by-model");
  }
});

/**
 * GET /api/tokens/trends
 * Weekly token usage trends.
 */
app.get("/api/tokens/trends", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(tokenTrends({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/tokens/trends");
  }
});

/**
 * GET /api/tokens/efficiency
 * Token efficiency metrics: tokens per file op, per redirection, ROI.
 */
app.get("/api/tokens/efficiency", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(tokenEfficiencyMetrics({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/tokens/efficiency");
  }
});

/**
 * GET /api/token-efficiency-score
 * Aggregate token efficiency scoring for Evaluation drill-down.
 */
app.get("/api/token-efficiency-score", (req, res) => {
  try {
    const opts = buildFilterOpts(req, res);
    if (opts === null) return;

    const sessions = listSessions(opts).filter((session) => session.turn_count >= 2);
    const scoredSessions = sessions
      .map((session) => ({
        sessionId: session.id,
        result: computeTokenEfficiencyScore(session.id),
      }))
      .filter(({ result }) => result && typeof result.score === "number");

    if (scoredSessions.length === 0) {
      return res.json({
        avgScore: 0,
        totalSessions: 0,
        components: { ratioScore: 0, turnScore: 0, cacheScore: 0 },
        topOptimizations: [],
      });
    }

    const componentTotals = scoredSessions.reduce((totals, { result }) => ({
      ratioScore: totals.ratioScore + (result.components?.ratioScore || 0),
      turnScore: totals.turnScore + (result.components?.turnScore || 0),
      cacheScore: totals.cacheScore + (result.components?.cacheScore || 0),
    }), { ratioScore: 0, turnScore: 0, cacheScore: 0 });

    const components = {
      ratioScore: Math.round(componentTotals.ratioScore / scoredSessions.length),
      turnScore: Math.round(componentTotals.turnScore / scoredSessions.length),
      cacheScore: Math.round(componentTotals.cacheScore / scoredSessions.length),
    };

    const optimizationPlaybook = [
      {
        id: "output-input-ratio",
        title: "Increase output yield",
        description: "Batch requirements up front and ask for fuller implementations to get more useful output per input token.",
        avgScore: components.ratioScore,
      },
      {
        id: "tokens-per-turn",
        title: "Reduce tokens per turn",
        description: "Tighten task scope and split exploratory follow-ups into separate sessions to keep productive turns lean.",
        avgScore: components.turnScore,
      },
      {
        id: "cache-utilization",
        title: "Improve cache reuse",
        description: "Reuse stable instructions and shared context so repeated prompts benefit from cached input tokens.",
        avgScore: components.cacheScore,
      },
    ];

    const avgScore = Math.round(
      scoredSessions.reduce((sum, { result }) => sum + result.score, 0) / scoredSessions.length
    );

    res.json({
      avgScore,
      totalSessions: scoredSessions.length,
      components,
      topOptimizations: optimizationPlaybook.sort((a, b) => a.avgScore - b.avgScore).slice(0, 3),
    });
  } catch (err) {
    handleRouteError(res, err, "GET /api/token-efficiency-score");
  }
});

/**
 * GET /api/tokens/correlations
 * Token cost correlated with work style, delegation, sprawl, redirections.
 */
app.get("/api/tokens/correlations", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    const opts = { repo, since, excludeIds: hiddenSessions };
    res.json({
      byWorkStyle: tokensByWorkStyle(opts),
      byRedirection: tokensPerRedirection(opts),
    });
  } catch (err) {
    handleRouteError(res, err, "GET /api/tokens/correlations");
  }
});

/**
 * GET /api/tokens/budget
 * Budget projection and usage alerts.
 */
app.get("/api/tokens/budget", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(budgetProjection({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/tokens/budget");
  }
});

/**
 * GET /api/tokens/tips
 * Prompt optimization tips based on token patterns.
 */
app.get("/api/tokens/tips", (req, res) => {
  try {
    const repo = validateRepo(req, res);
    if (repo === null) return;
    const since = validateTimeframe(req, res);
    if (since === null) return;
    res.json(promptOptimizationTips({ repo, since, excludeIds: hiddenSessions }));
  } catch (err) {
    handleRouteError(res, err, "GET /api/tokens/tips");
  }
});

/**
 * GET /api/sessions/:id/tokens
 * Per-session token breakdown (turn-by-turn).
 */
app.get("/api/sessions/:id/tokens", (req, res) => {
  try {
    const result = analyzeSessionTokens(req.params.id);
    if (!result) {
      return res.status(404).json({ error: "Session not found or has no turns" });
    }
    res.json(result);
  } catch (err) {
    handleRouteError(res, err, "GET /api/sessions/:id/tokens");
  }
});

/**
 * GET /api/chronicle/tips
 * Chronicle-style personalized coaching tips.
 */
app.get("/api/chronicle/tips", (req, res) => {
  try {
    const opts = buildFilterOpts(req, res);
    if (opts === null) return;
    res.json(generateTips(opts));
  } catch (err) {
    handleRouteError(res, err, "GET /api/chronicle/tips");
  }
});

/**
 * GET /api/chronicle/improve/:sessionId
 * Chronicle-style per-session improvement advice.
 */
app.get("/api/chronicle/improve/:sessionId", (req, res) => {
  try {
    const result = generateImprove(req.params.sessionId);
    if (!result) {
      return res.status(404).json({ error: "Session not found" });
    }
    res.json(result);
  } catch (err) {
    handleRouteError(res, err, "GET /api/chronicle/improve/:sessionId");
  }
});

// -- Live Feed ---------------------------------------------
/**
 * GET /api/live/feed?since=<ISO>
 * Returns recent turns annotated with redirection pattern matches.
 */
app.get("/api/live/feed", (req, res) => {
  try {
    let since;
    if (req.query.since) {
      // Validate ISO 8601 date format
      const d = new Date(req.query.since);
      if (isNaN(d.getTime())) {
        return res.status(400).json({ error: "Invalid since parameter. Expected ISO 8601 date." });
      }
      since = d.toISOString();
    } else {
      since = new Date(Date.now() - 3600_000).toISOString();
    }
    const db = getDb();
    const rows = db
      .prepare(
        `SELECT t.session_id, t.turn_index, t.user_message, t.timestamp,
                s.repository, s.branch
         FROM turns t
         JOIN sessions s ON t.session_id = s.id
         WHERE t.timestamp > ?
         ORDER BY t.timestamp DESC
         LIMIT 200`
      )
      .all(since);

    const turns = rows.map((row) => {
      const patterns = matchPatterns(row.user_message);
      return {
        sessionId: row.session_id,
        turnIndex: row.turn_index,
        timestamp: row.timestamp,
        userMessage: row.user_message ? row.user_message.slice(0, 300) : "",
        repository: row.repository,
        branch: row.branch,
        patterns,
        maxWeight: patterns.reduce((max, p) => Math.max(max, p.weight), 0),
      };
    });

    res.json({ turns, serverTime: new Date().toISOString(), categories: REDIRECTION_CATEGORIES });
  } catch (err) {
    handleRouteError(res, err, "unknown");
  }
});

// -- Global error handler ----------------------------------
app.use((err, _req, res, _next) => {
  handleRouteError(res, err, "unknown");
});

// -- SPA fallback ------------------------------------------
app.get("/{*path}", (req, res) => {
  if (req.path.startsWith("/api/")) {
    return res.status(404).json({ error: "Not found" });
  }
  res.sendFile("index.html", { root: uiDist });
});

// -- Start -------------------------------------------------
const server = app.listen(PORT, "127.0.0.1", () => {
  log.info(`Copilot Insights dashboard: http://localhost:${PORT}`);
});

server.on("error", (err) => {
  if (err.code === "EADDRINUSE") {
    log.error(`Port ${PORT} is already in use. Try one of these:`);
    log.error(`  1. Stop the other process using port ${PORT}`);
    log.error(`  2. Run with a different port: PORT=${Number(PORT) + 1} npm start`);
    process.exit(1);
  }
  if (err.code === "EACCES") {
    log.error(`Permission denied on port ${PORT}. Try a port above 1024.`);
    process.exit(1);
  }
  throw err;
});
