// Core analysis engine — scans session turns and produces a redirection report.

import {
  listSessions,
  getSessionTurns,
  getSession,
  getFileEditCounts,
  batchGetSessionTurns,
  batchGetFileEditCounts,
} from "./db.mjs";
import { matchPatterns } from "./patterns.mjs";
import { isAutoGenerated, cleanSummary } from "./autogenerated.mjs";

function buildSessionReport(session, turns, fileEdits) {
  if (!session) return null;

  const redirections = [];
  let totalWeight = 0;
  let autoGeneratedCount = 0;

  for (const turn of turns) {
    if (!turn.user_message) continue;

    // Skip auto-generated turns (system notifications, cross-session msgs, etc.)
    if (isAutoGenerated(turn.user_message)) {
      autoGeneratedCount++;
      continue;
    }

    const matches = matchPatterns(turn.user_message);
    if (matches.length > 0) {
      const turnWeight = matches.reduce((sum, m) => sum + m.weight, 0);
      totalWeight += turnWeight;
      redirections.push({
        turnIndex: turn.turn_index,
        timestamp: turn.timestamp,
        message: turn.user_message.substring(0, 300),
        matches,
        weight: turnWeight,
      });
    }
  }

  // Detect file thrashing (same file edited 3+ times)
  const thrashedFiles = fileEdits.filter((f) => f.edit_count >= 3);

  // Compute category breakdown
  const categoryBreakdown = {};
  for (const r of redirections) {
    for (const m of r.matches) {
      if (!categoryBreakdown[m.category]) {
        categoryBreakdown[m.category] = { count: 0, weight: 0 };
      }
      categoryBreakdown[m.category].count++;
      categoryBreakdown[m.category].weight += m.weight;
    }
  }

  // Redirection rate: fraction of human user turns that contain a redirection
  const userTurnCount = turns.filter((t) => t.user_message).length;
  const humanTurnCount = userTurnCount - autoGeneratedCount;
  const redirectionRate =
    humanTurnCount > 0 ? redirections.length / humanTurnCount : 0;

  const createdAt = session.created_at ?? session.createdAt ?? null;
  const turnCount = session.turn_count ?? session.turnCount ?? turns.length;

  return {
    session: {
      id: session.id,
      repository: session.repository,
      branch: session.branch,
      summary: cleanSummary(session.summary, turns),
      createdAt,
      turnCount,
    },
    stats: {
      totalRedirections: redirections.length,
      totalWeight,
      userTurnCount: humanTurnCount,
      autoGeneratedCount,
      redirectionRate,
      thrashedFileCount: thrashedFiles.length,
    },
    categoryBreakdown,
    redirections,
    thrashedFiles,
  };
}

/**
 * Analyze a single session for redirection signals.
 * Returns a structured report with per-turn matches and aggregate stats.
 */
export function analyzeSession(sessionId) {
  const session = getSession(sessionId);
  if (!session) return null;
  return buildSessionReport(session, getSessionTurns(sessionId), getFileEditCounts(sessionId));
}

/**
 * Analyze multiple recent sessions and return a summary.
 */
export function analyzeRecent({ repo, limit = 500, since, excludeIds, includeAll = false } = {}) {
  const sessions = listSessions({ repo, limit, since, excludeIds });
  const results = [];
  const analyzableSessions = includeAll
    ? sessions
    : sessions.filter((session) => session.turn_count >= 2);
  const sessionIds = analyzableSessions.map((session) => session.id);
  const turnsBySession = batchGetSessionTurns(sessionIds);
  const fileEditsBySession = batchGetFileEditCounts(sessionIds);

  for (const session of analyzableSessions) {
    const report = buildSessionReport(
      session,
      turnsBySession.get(session.id) || [],
      fileEditsBySession.get(session.id) || []
    );
    if (report && (includeAll || report.stats.totalRedirections > 0)) {
      results.push(report);
    }
  }

  // Sort by redirection weight (most problematic first)
  results.sort((a, b) => {
    if (b.stats.totalWeight !== a.stats.totalWeight) return b.stats.totalWeight - a.stats.totalWeight;
    return String(b.session.createdAt || "").localeCompare(String(a.session.createdAt || ""));
  });

  const rateBase = includeAll
    ? results
    : results.filter((result) => result.stats.totalRedirections > 0);

  // Aggregate stats across all sessions
  const aggregate = {
    sessionsAnalyzed: includeAll ? results.length : sessions.length,
    sessionsWithRedirections: results.filter((result) => result.stats.totalRedirections > 0).length,
    totalRedirections: results.reduce(
      (s, r) => s + r.stats.totalRedirections,
      0
    ),
    avgRedirectionRate:
      rateBase.length > 0
        ? rateBase.reduce((s, r) => s + r.stats.redirectionRate, 0) /
          rateBase.length
        : 0,
    categoryTotals: {},
  };

  for (const r of results) {
    for (const [cat, data] of Object.entries(r.categoryBreakdown)) {
      if (!aggregate.categoryTotals[cat]) {
        aggregate.categoryTotals[cat] = { count: 0, weight: 0 };
      }
      aggregate.categoryTotals[cat].count += data.count;
      aggregate.categoryTotals[cat].weight += data.weight;
    }
  }

  return { aggregate, sessions: results };
}

/**
 * Find the most common redirection patterns across sessions.
 */
export function findTopPatterns({ repo, limit = 500, since, excludeIds } = {}) {
  const { sessions } = analyzeRecent({ repo, limit, since, excludeIds });

  const patternCounts = {};
  for (const s of sessions) {
    for (const r of s.redirections) {
      for (const m of r.matches) {
        const key = `${m.category}::${m.label}`;
        if (!patternCounts[key]) {
          patternCounts[key] = {
            category: m.category,
            label: m.label,
            count: 0,
            weight: 0,
            examples: [],
          };
        }
        patternCounts[key].count++;
        patternCounts[key].weight += m.weight;
        if (patternCounts[key].examples.length < 3) {
          patternCounts[key].examples.push({
            sessionId: s.session.id,
            repo: s.session.repository,
            message: r.message.substring(0, 120),
          });
        }
      }
    }
  }

  return Object.values(patternCounts).sort((a, b) => b.count - a.count);
}
