// Detect auto-generated user messages injected by Copilot infrastructure.
// These are system notifications, cross-session messages, plan-mode wrappers,
// agent-merge ticks, and other machine-generated content that should not be
// analyzed as human prompting behavior.

/**
 * Tag metadata for auto-generated turns.
 */
export const AUTOGENERATED_TAG = {
  type: "auto_generated",
  emoji: "🤖",
  label: "Auto-generated",
  color: "#6e7681",
  detail: "System-generated message, not a human prompt",
};

// Patterns that indicate a message was injected by the Copilot runtime
const PLAN_PREFIX_RE = /^\[\[PLAN\]\]/;
const SYSTEM_NOTIFICATION_RE = /<system_notification\b/i;
const CROSS_SESSION_RE = /<cross_session_message\b/i;
const AGENT_MERGE_RE = /<agent_merge_tick\b/i;
const AUTOMATED_TAG_RE = /<automated_\w+/i;
const DATETIME_ONLY_RE = /^<current_datetime>[^<]*<\/current_datetime>\s*$/;

// Strip all XML/HTML tags to isolate user-typed content
function stripTags(msg) {
  return msg
    .replace(/<[^>]*>[\s\S]*?<\/[^>]*>/gi, "")
    .replace(/<[^>]+>/g, " ")
    .trim();
}

/**
 * Returns true if the user_message was auto-generated by Copilot infrastructure
 * rather than typed by a human.
 *
 * @param {string} msg - The raw user_message from a session turn.
 * @returns {boolean}
 */
export function isAutoGenerated(msg) {
  if (!msg || typeof msg !== "string") return false;

  const trimmed = msg.trim();

  // Explicit structural markers
  if (PLAN_PREFIX_RE.test(trimmed)) return true;
  if (SYSTEM_NOTIFICATION_RE.test(trimmed)) return true;
  if (CROSS_SESSION_RE.test(trimmed)) return true;
  if (AGENT_MERGE_RE.test(trimmed)) return true;
  if (AUTOMATED_TAG_RE.test(trimmed)) return true;

  // Messages that are purely a <current_datetime> tag with nothing else
  if (DATETIME_ONLY_RE.test(trimmed)) return true;

  // Messages that are entirely XML/system tags with no meaningful user content
  const stripped = stripTags(trimmed);
  if (stripped.length === 0 && trimmed.length > 0) return true;

  return false;
}

/**
 * If a session summary is auto-generated, return a cleaned version.
 * Falls back to the first human turn from the provided turns array,
 * or null if none exists.
 *
 * @param {string|null} summary - The raw session summary from the DB.
 * @param {Array<{user_message: string}>} [turns] - Session turns to find a human fallback.
 * @returns {string|null}
 */
export function cleanSummary(summary, turns = []) {
  if (!summary || !isAutoGenerated(summary)) return summary;

  // Find the first human turn as a replacement
  for (const t of turns) {
    if (t.user_message && !isAutoGenerated(t.user_message)) {
      return t.user_message.substring(0, 200);
    }
  }
  return null;
}
