// Token usage estimation and cost analysis.
// Reads real token data from JSONL session-state files when available,
// falls back to text-based estimation, and auto-upgrades to real data
// from the events table if Copilot CLI ever stores it locally.

import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { getDb, hasTable, listSessions, getSessionTurns } from "./db.mjs";
import { isAutoGenerated } from "./autogenerated.mjs";

// ── JSONL Session-State Reader ──────────────────────────────
// Copilot CLI writes events.jsonl files per session with real token data.

const SESSION_STATE_PATH =
  process.env.COPILOT_SESSION_STATE_PATH ||
  join(homedir(), ".copilot", "session-state");

function parseJsonlFile(filePath) {
  try {
    const content = readFileSync(filePath, "utf-8");
    const results = [];
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      try { results.push(JSON.parse(trimmed)); } catch { /* skip malformed */ }
    }
    return results;
  } catch { return []; }
}

/**
 * Read real token usage from JSONL session-state files.
 * Returns null if no usable data found.
 */
function readSessionTokensFromJsonl(sessionId) {
  if (!sessionId) return null;
  const sessionDir = join(SESSION_STATE_PATH, sessionId);
  if (!existsSync(sessionDir)) return null;

  let jsonlFiles;
  try {
    const all = readdirSync(sessionDir);
    const wellKnown = ["events.jsonl", "turns.jsonl"];
    const preferred = wellKnown.filter((f) => all.includes(f));
    const rest = all.filter((f) => f.endsWith(".jsonl") && !preferred.includes(f));
    jsonlFiles = [...preferred, ...rest];
  } catch { return null; }

  if (jsonlFiles.length === 0) return null;

  const assistantMessages = [];
  let sessionModel = null;

  for (const file of jsonlFiles) {
    const objects = parseJsonlFile(join(sessionDir, file));
    for (const obj of objects) {
      // Extract model from session events
      if (obj.type === "session.model_change" && obj.data?.newModel) {
        sessionModel = obj.data.newModel;
      }
      // Extract token data from assistant messages
      if (obj.type === "assistant.message" && typeof obj.data?.outputTokens === "number") {
        assistantMessages.push({
          turnIndex: assistantMessages.length,
          outputTokens: obj.data.outputTokens,
          model: sessionModel,
        });
      }
    }
  }

  if (assistantMessages.length === 0) return null;

  let totalOutput = 0;
  for (const m of assistantMessages) totalOutput += m.outputTokens;

  return {
    source: "jsonl",
    model: sessionModel,
    turns: assistantMessages,
    totals: { outputTokens: totalOutput },
  };
}

// ── Token Estimation ─────────────────────────────────────────
// Standard LLM approximation: ~4 characters per token for English text.
// ~75% accurate — clearly labeled as "estimated" in all outputs.

const CHARS_PER_TOKEN = 4;

/**
 * Estimate token count from text.
 * @param {string} text
 * @returns {number}
 */
export function estimateTokens(text) {
  if (!text) return 0;
  return Math.ceil(text.length / CHARS_PER_TOKEN);
}

// ── Model Pricing ────────────────────────────────────────────
// Prices per 1M tokens (USD) — from GitHub Copilot official pricing:
// https://docs.github.com/en/copilot/reference/copilot-billing/models-and-pricing
// 1 AI credit = $0.01 USD. These are the per-token rates for usage-based billing.
// Hardcoded as fallback; fetchLivePricing() fetches live data on page load.

export const MODEL_PRICING = {
  // OpenAI models
  "gpt-4.1":               { input: 2.00,  output: 8.00,   cachedInput: 0.50 },
  "gpt-5-mini":            { input: 0.25,  output: 2.00,   cachedInput: 0.025 },
  "gpt-5.2":               { input: 1.75,  output: 14.00,  cachedInput: 0.175 },
  "gpt-5.2-codex":         { input: 1.75,  output: 14.00,  cachedInput: 0.175 },
  "gpt-5.3-codex":         { input: 1.75,  output: 14.00,  cachedInput: 0.175 },
  "gpt-5.4":               { input: 2.50,  output: 15.00,  cachedInput: 0.25 },
  "gpt-5.4-mini":          { input: 0.75,  output: 4.50,   cachedInput: 0.075 },
  "gpt-5.4-nano":          { input: 0.20,  output: 1.25,   cachedInput: 0.02 },
  "gpt-5.5":               { input: 5.00,  output: 30.00,  cachedInput: 0.50 },
  // Anthropic models (also have cacheWrite cost, tracked separately)
  "claude-haiku-4.5":      { input: 1.00,  output: 5.00,   cachedInput: 0.10, cacheWrite: 1.25 },
  "claude-sonnet-4":       { input: 3.00,  output: 15.00,  cachedInput: 0.30, cacheWrite: 3.75 },
  "claude-sonnet-4.5":     { input: 3.00,  output: 15.00,  cachedInput: 0.30, cacheWrite: 3.75 },
  "claude-sonnet-4.6":     { input: 3.00,  output: 15.00,  cachedInput: 0.30, cacheWrite: 3.75 },
  "claude-opus-4.5":       { input: 5.00,  output: 25.00,  cachedInput: 0.50, cacheWrite: 6.25 },
  "claude-opus-4.6":       { input: 5.00,  output: 25.00,  cachedInput: 0.50, cacheWrite: 6.25 },
  "claude-opus-4.7":       { input: 5.00,  output: 25.00,  cachedInput: 0.50, cacheWrite: 6.25 },
  // Google models
  "gemini-2.5-pro":        { input: 1.25,  output: 10.00,  cachedInput: 0.125 },
  "gemini-3-flash":        { input: 0.50,  output: 3.00,   cachedInput: 0.05 },
  "gemini-3.1-pro":        { input: 2.00,  output: 12.00,  cachedInput: 0.20 },
  // xAI models
  "grok-code-fast-1":      { input: 0.20,  output: 1.50,   cachedInput: 0.02 },
  // Fine-tuned (GitHub) models
  "raptor-mini":           { input: 0.25,  output: 2.00,   cachedInput: 0.025 },
  "goldeneye":             { input: 1.25,  output: 10.00,  cachedInput: 0.125 },
};

// Fallback for unknown models — uses mid-tier Sonnet-class pricing
const DEFAULT_PRICING = { input: 3.00, output: 15.00, cachedInput: 0.30 };

// ── Live Pricing Fetcher ─────────────────────────────────────
// Fetches current pricing from GitHub Copilot docs on page load.
// Caches for 1 hour. Falls back to hardcoded MODEL_PRICING on failure.

const PRICING_URL = "https://docs.github.com/en/copilot/reference/copilot-billing/models-and-pricing";
const CACHE_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours

let livePricingCache = null;
let livePricingFetchedAt = 0;

/**
 * Normalize a display model name to a slug (e.g., "Claude Sonnet 4.6" → "claude-sonnet-4.6").
 */
function normalizeModelName(displayName) {
  return displayName
    .replace(/\[.*?\]/g, "")   // remove footnote refs like [1]
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "-");
}

/**
 * Parse pricing tables from the GitHub docs page (HTML or simplified text).
 * Handles both raw HTML (<td>$2.50</td>) and simplified markdown text.
 * Standard columns: Model | Release status | Category | Input | Cached input | Output
 * Anthropic adds: Cache write between Cached input and Output.
 */
function parsePricingFromPage(text) {
  const models = {};

  // Normalize HTML entities: $ → $, etc.
  const normalized = text
    .replace(/&#?\w+;/g, (m) => {
      if (m === "$" || m === "$") return "$";
      if (m === "&amp;") return "&";
      if (m === "&lt;") return "<";
      if (m === "&gt;") return ">";
      return m;
    });

  // Find the pricing tables section — use heading ids to skip nav sidebars
  let pricingStart = normalized.indexOf('id="pricing-tables"');
  if (pricingStart === -1) pricingStart = normalized.lastIndexOf("Pricing tables");
  if (pricingStart === -1) return null;
  let pricingEnd = normalized.indexOf('id="code-completions"', pricingStart);
  if (pricingEnd === -1) pricingEnd = normalized.indexOf("Code completions", pricingStart + 100);
  const section = normalized.slice(pricingStart, pricingEnd > 0 ? pricingEnd : undefined);

  const vendors = [
    { name: "OpenAI", hasCacheWrite: false },
    { name: "Anthropic", hasCacheWrite: true },
    { name: "Google", hasCacheWrite: false },
    { name: "xAI", hasCacheWrite: false },
    { name: "Fine-tuned", hasCacheWrite: false },
  ];

  // Extract table rows — works for both HTML <tr>...</tr> and text lines
  const rowPattern = /<tr[^>]*>([\s\S]*?)<\/tr>/gi;
  const cellPattern = /<td[^>]*>([\s\S]*?)<\/td>/gi;

  for (const vendor of vendors) {
    const vendorIdx = section.indexOf(vendor.name);
    if (vendorIdx === -1) continue;

    let endIdx = section.length;
    for (const other of vendors) {
      if (other.name === vendor.name) continue;
      const otherIdx = section.indexOf(other.name, vendorIdx + vendor.name.length);
      if (otherIdx > 0 && otherIdx < endIdx) endIdx = otherIdx;
    }

    const vendorSection = section.slice(vendorIdx, endIdx);

    // Try HTML table parsing first
    const rows = [...vendorSection.matchAll(rowPattern)];
    if (rows.length > 0) {
      for (const row of rows) {
        const cells = [...row[1].matchAll(cellPattern)].map(
          (c) => c[1].replace(/<sup[\s\S]*?<\/sup>/gi, "").replace(/<[^>]+>/g, "").trim()
        );
        if (cells.length < 6) continue;

        const modelName = cells[0];
        const category = cells[2];
        const prices = cells.slice(3).map((c) => {
          const m = c.match(/\$?([\d.]+)/);
          return m ? parseFloat(m[1]) : null;
        }).filter((p) => p !== null);

        if (prices.length < 3 || !modelName || modelName.length < 3) continue;
        const slug = normalizeModelName(modelName);
        const cat = ["powerful", "versatile", "lightweight"].includes(category?.toLowerCase())
          ? category.toLowerCase() : null;

        if (vendor.hasCacheWrite && prices.length >= 4) {
          models[slug] = { input: prices[0], cachedInput: prices[1], cacheWrite: prices[2], output: prices[3], vendor: vendor.name, category: cat };
        } else {
          models[slug] = { input: prices[0], cachedInput: prices[1], output: prices[2], vendor: vendor.name, category: cat };
        }
      }
    } else {
      // Fallback: text-based parsing (simplified markdown)
      const pricePattern = /\$(\d+\.?\d*)/g;
      for (const line of vendorSection.split("\n")) {
        const prices = [];
        let match;
        while ((match = pricePattern.exec(line)) !== null) prices.push(parseFloat(match[1]));
        pricePattern.lastIndex = 0;
        if (prices.length < 3) continue;

        const statusWords = ["GA", "Public preview", "Preview", "Beta"];
        let mn = line;
        for (const sw of statusWords) { const idx = mn.indexOf(sw); if (idx > 0) { mn = mn.slice(0, idx); break; } }
        mn = mn.replace(/\[.*?\]/g, "").replace(/\d+$/, "").trim();
        if (!mn || mn.length < 3) continue;

        const slug = normalizeModelName(mn);
        const categories = ["Powerful", "Versatile", "Lightweight"];
        let cat = null;
        for (const c of categories) { if (line.includes(c)) { cat = c.toLowerCase(); break; } }

        if (vendor.hasCacheWrite && prices.length >= 4) {
          models[slug] = { input: prices[0], cachedInput: prices[1], cacheWrite: prices[2], output: prices[3], vendor: vendor.name, category: cat };
        } else {
          models[slug] = { input: prices[0], cachedInput: prices[1], output: prices[2], vendor: vendor.name, category: cat };
        }
      }
    }
  }

  return Object.keys(models).length > 0 ? models : null;
}

/**
 * Fetch live pricing from GitHub docs. Returns parsed models or null on failure.
 * Results are cached for 1 hour.
 */
export async function fetchLivePricing() {
  const now = Date.now();
  if (livePricingCache && (now - livePricingFetchedAt) < CACHE_TTL_MS) {
    return livePricingCache;
  }

  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 10000);

    const resp = await fetch(PRICING_URL, {
      signal: controller.signal,
      headers: { "Accept": "text/html", "User-Agent": "copilot-insights/1.0" },
    });
    clearTimeout(timeout);

    if (!resp.ok) return null;
    const html = await resp.text();

    const parsed = parsePricingFromPage(html);
    if (parsed && Object.keys(parsed).length >= 5) {
      livePricingCache = {
        models: parsed,
        fetchedAt: new Date().toISOString(),
        source: PRICING_URL,
        modelCount: Object.keys(parsed).length,
      };
      livePricingFetchedAt = now;
      return livePricingCache;
    }
  } catch { /* fetch failed — use fallback */ }
  return null;
}

/**
 * Get the current effective pricing table.
 * Returns live pricing if available, otherwise the hardcoded fallback.
 */
export function getLivePricingOrFallback() {
  if (livePricingCache) {
    return {
      models: livePricingCache.models,
      source: "live",
      fetchedAt: livePricingCache.fetchedAt,
      url: PRICING_URL,
    };
  }
  return {
    models: MODEL_PRICING,
    source: "hardcoded",
    fetchedAt: null,
    url: PRICING_URL,
  };
}

/**
 * Get pricing for a model, with fallback for unknown models.
 * "auto" resolves to default pricing since the actual model isn't known.
 */
export function getModelPricing(model) {
  if (!model || model === "auto" || model === "unknown") return DEFAULT_PRICING;
  // Normalize: lowercase, trim
  const normalized = model.toLowerCase().trim();
  if (MODEL_PRICING[normalized]) return MODEL_PRICING[normalized];
  // Prefix match (e.g., "claude-sonnet-4.6-xxx" matches "claude-sonnet-4.6")
  const key = Object.keys(MODEL_PRICING).find((k) => normalized.startsWith(k));
  return key ? MODEL_PRICING[key] : DEFAULT_PRICING;
}

/**
 * Estimate cost in USD from token counts and model.
 */
export function estimateCost(inputTokens, outputTokens, model, cachedInputTokens = 0) {
  const pricing = getModelPricing(model);
  const freshInput = inputTokens - cachedInputTokens;
  return (
    (freshInput / 1_000_000) * pricing.input +
    (cachedInputTokens / 1_000_000) * pricing.cachedInput +
    (outputTokens / 1_000_000) * pricing.output
  );
}

// ── Real Token Data (events table) ──────────────────────────

/**
 * Get real token usage from the events table for a session.
 * Returns null if events table is unavailable.
 */
export function getRealTokenUsage(sessionId) {
  if (!hasTable("events")) return null;
  const db = getDb();
  try {
    return db
      .prepare(
        `SELECT usage_model, usage_input_tokens, usage_output_tokens,
                usage_cache_read_tokens, usage_cache_write_tokens,
                usage_cost, usage_duration
         FROM events
         WHERE session_id = ? AND usage_input_tokens IS NOT NULL
         ORDER BY rowid`
      )
      .all(sessionId);
  } catch {
    return null;
  }
}

/**
 * Get the model used in a session from the events table.
 */
export function getSessionModel(sessionId) {
  if (!hasTable("events")) return null;
  const db = getDb();
  try {
    const row = db
      .prepare(
        `SELECT usage_model FROM events
         WHERE session_id = ? AND usage_model IS NOT NULL
         LIMIT 1`
      )
      .get(sessionId);
    return row?.usage_model || null;
  } catch {
    return null;
  }
}

// ── Per-Session Token Analysis ──────────────────────────────

/**
 * Analyze token usage for a single session.
 * Priority: 1) JSONL real data, 2) Events table, 3) Text estimation.
 */
export function analyzeSessionTokens(sessionId) {
  const turns = getSessionTurns(sessionId);
  if (!turns || turns.length === 0) return null;

  // Try JSONL first (best source — real output token counts)
  const jsonlData = readSessionTokensFromJsonl(sessionId);

  // Then try events table
  const realUsage = !jsonlData ? getRealTokenUsage(sessionId) : null;
  const model = jsonlData?.model || getSessionModel(sessionId);

  // Determine data source
  const hasJsonl = jsonlData && jsonlData.turns.length > 0;
  const hasEvents = !hasJsonl && realUsage && realUsage.length > 0;
  const isEstimated = !hasJsonl && !hasEvents;
  const source = hasJsonl ? "jsonl" : hasEvents ? "events" : "estimated";

  let totalInput = 0;
  let totalOutput = 0;
  let totalCachedInput = 0;
  const perTurn = [];

  if (hasJsonl) {
    // Use JSONL real output tokens + estimate input from text
    totalOutput = jsonlData.totals.outputTokens;
    for (const turn of turns) {
      if (isAutoGenerated(turn.user_message)) continue;
      const inputEst = estimateTokens(turn.user_message);
      totalInput += inputEst;
      const jsonlTurn = jsonlData.turns[perTurn.length];
      const outputReal = jsonlTurn?.outputTokens || estimateTokens(turn.assistant_response);
      perTurn.push({
        turnIndex: turn.turn_index,
        inputTokens: inputEst,
        outputTokens: outputReal,
        total: inputEst + outputReal,
        estimated: !jsonlTurn,
        preview: (turn.user_message || "").slice(0, 80),
      });
    }
  } else if (hasEvents) {
    // Use real token data from events table
    for (const evt of realUsage) {
      totalInput += evt.usage_input_tokens || 0;
      totalOutput += evt.usage_output_tokens || 0;
      totalCachedInput += evt.usage_cache_read_tokens || 0;
    }
    for (const turn of turns) {
      if (isAutoGenerated(turn.user_message)) continue;
      const inputEst = estimateTokens(turn.user_message);
      const outputEst = estimateTokens(turn.assistant_response);
      perTurn.push({
        turnIndex: turn.turn_index,
        inputTokens: inputEst,
        outputTokens: outputEst,
        total: inputEst + outputEst,
        estimated: true,
        preview: (turn.user_message || "").slice(0, 80),
      });
    }
  } else {
    // Estimate from text
    for (const turn of turns) {
      if (isAutoGenerated(turn.user_message)) continue;
      const inputEst = estimateTokens(turn.user_message);
      const outputEst = estimateTokens(turn.assistant_response);
      totalInput += inputEst;
      totalOutput += outputEst;
      perTurn.push({
        turnIndex: turn.turn_index,
        inputTokens: inputEst,
        outputTokens: outputEst,
        total: inputEst + outputEst,
        estimated: true,
        preview: (turn.user_message || "").slice(0, 80),
      });
    }
  }

  const total = totalInput + totalOutput;
  const cost = estimateCost(totalInput, totalOutput, model, totalCachedInput);

  return {
    sessionId,
    model: model || "unknown",
    isEstimated,
    source,
    tokens: { input: totalInput, output: totalOutput, cached: totalCachedInput, total },
    estimatedCost: cost,
    perTurn,
    turnCount: perTurn.length,
    avgTokensPerTurn: perTurn.length > 0 ? Math.round(total / perTurn.length) : 0,
  };
}

// ── Batch Token Analysis ────────────────────────────────────

/**
 * Analyze token usage across multiple sessions.
 */
export function analyzeTokensBatch({ repo, since, excludeIds } = {}) {
  const sessions = listSessions({ repo, since, excludeIds });
  if (sessions.length === 0) {
    return {
      sessionsAnalyzed: 0,
      isEstimated: true,
      totals: { input: 0, output: 0, cached: 0, total: 0 },
      estimatedCost: 0,
      avgTokensPerSession: 0,
      avgCostPerSession: 0,
      byModel: {},
      sessions: [],
    };
  }

  let totalInput = 0;
  let totalOutput = 0;
  let totalCached = 0;
  let totalCost = 0;
  let totalInputCost = 0;
  let totalOutputCost = 0;
  let anyEstimated = false;
  const byModel = {};
  const sessionResults = [];

  for (const s of sessions) {
    const result = analyzeSessionTokens(s.id);
    if (!result) continue;

    if (result.isEstimated) anyEstimated = true;
    totalInput += result.tokens.input;
    totalOutput += result.tokens.output;
    totalCached += result.tokens.cached;
    totalCost += result.estimatedCost;

    // Track input vs output cost per session using its actual model pricing
    const pricing = getModelPricing(result.model);
    const freshIn = result.tokens.input - result.tokens.cached;
    totalInputCost += (freshIn / 1_000_000) * pricing.input + (result.tokens.cached / 1_000_000) * pricing.cachedInput;
    totalOutputCost += (result.tokens.output / 1_000_000) * pricing.output;

    const m = result.model || "unknown";
    if (!byModel[m]) {
      byModel[m] = { model: m, sessions: 0, input: 0, output: 0, cached: 0, total: 0, cost: 0 };
    }
    byModel[m].sessions += 1;
    byModel[m].input += result.tokens.input;
    byModel[m].output += result.tokens.output;
    byModel[m].cached += result.tokens.cached;
    byModel[m].total += result.tokens.total;
    byModel[m].cost += result.estimatedCost;

    sessionResults.push({
      sessionId: s.id,
      repository: s.repository,
      branch: s.branch,
      summary: s.summary,
      createdAt: s.created_at,
      model: result.model,
      tokens: result.tokens,
      estimatedCost: result.estimatedCost,
      turnCount: result.turnCount,
      avgTokensPerTurn: result.avgTokensPerTurn,
    });
  }

  const total = totalInput + totalOutput;
  const analyzed = sessionResults.length;

  return {
    sessionsAnalyzed: analyzed,
    isEstimated: anyEstimated,
    totals: { input: totalInput, output: totalOutput, cached: totalCached, total },
    estimatedCost: totalCost,
    costBreakdown: { input: totalInputCost, output: totalOutputCost },
    avgTokensPerSession: analyzed > 0 ? Math.round(total / analyzed) : 0,
    avgCostPerSession: analyzed > 0 ? totalCost / analyzed : 0,
    byModel: Object.values(byModel).sort((a, b) => b.total - a.total),
    sessions: sessionResults.sort((a, b) => b.tokens.total - a.tokens.total),
  };
}
